<?php


/**
 * This class defines the structure of the 'alpza_miembro_asociados' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Nov 24 15:15:37 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AlpzaMiembroAsociadosTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AlpzaMiembroAsociadosTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
		// attributes
		$this->setName('alpza_miembro_asociados');
		$this->setPhpName('AlpzaMiembroAsociados');
		$this->setClassname('AlpzaMiembroAsociados');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID_ALPZA_MIEMBRO_ASOCIADOS', 'IdAlpzaMiembroAsociados', 'INTEGER', true, null, null);
		$this->addForeignKey('ALPZA_MIEMBRO_ID_ALPZA_MIEMBRO', 'AlpzaMiembroIdAlpzaMiembro', 'INTEGER', 'alpza_miembro', 'ID_ALPZA_MIEMBRO', true, null, null);
		$this->addColumn('NOMBRE_FORMAL', 'NombreFormal', 'VARCHAR', false, 100, null);
		$this->addColumn('SIGLA', 'Sigla', 'VARCHAR', false, 45, null);
		$this->addColumn('TIPO_INSTITUCION', 'TipoInstitucion', 'VARCHAR', false, 100, null);
		$this->addColumn('NUMERO_IDENTIFICACION', 'NumeroIdentificacion', 'VARCHAR', false, 100, null);
		$this->addColumn('ANO_FUNDACION', 'AnoFundacion', 'DATE', false, null, null);
		$this->addColumn('ANO_INGRESO_ALPZA', 'AnoIngresoAlpza', 'DATE', false, null, null);
		$this->addColumn('DIRECTOR_NOMBRE', 'DirectorNombre', 'VARCHAR', false, 100, null);
		$this->addColumn('DIRECTOR_EMAIL', 'DirectorEmail', 'VARCHAR', false, 100, null);
		$this->addColumn('DELEGADO_NOMBRE', 'DelegadoNombre', 'VARCHAR', false, 100, null);
		$this->addColumn('DELEGADO_APELLIDO', 'DelegadoApellido', 'VARCHAR', false, 100, null);
		$this->addColumn('DELEGADO_CARGO', 'DelegadoCargo', 'VARCHAR', false, 100, null);
		$this->addColumn('DELEGADO_PROFESION', 'DelegadoProfesion', 'VARCHAR', false, 100, null);
		$this->addColumn('DELEGADO_EMAIL', 'DelegadoEmail', 'VARCHAR', false, 100, null);
		$this->addColumn('LOGO', 'Logo', 'VARCHAR', false, 100, null);
		$this->addColumn('DIRECCION', 'Direccion', 'VARCHAR', false, 100, null);
		$this->addColumn('CODIGO_POSTAL', 'CodigoPostal', 'VARCHAR', false, 100, null);
		$this->addColumn('PAIS', 'Pais', 'VARCHAR', false, 100, null);
		$this->addColumn('TELEFONO_COD_CIUDAD', 'TelefonoCodCiudad', 'VARCHAR', false, 45, null);
		$this->addColumn('TELEFONO_COD_PAIS', 'TelefonoCodPais', 'VARCHAR', false, 45, null);
		$this->addColumn('TELEFONO', 'Telefono', 'VARCHAR', false, 45, null);
		$this->addColumn('CELULAR', 'Celular', 'VARCHAR', false, 45, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', false, 45, null);
		$this->addColumn('FAX', 'Fax', 'VARCHAR', false, 45, null);
		$this->addColumn('SITIO_WEB', 'SitioWeb', 'VARCHAR', false, 254, null);
		$this->addColumn('DESCRIPCION', 'Descripcion', 'LONGVARCHAR', false, null, null);
		$this->addColumn('MISION', 'Mision', 'LONGVARCHAR', false, null, null);
		$this->addColumn('VISION', 'Vision', 'LONGVARCHAR', false, null, null);
		$this->addColumn('OBJETIVOS', 'Objetivos', 'LONGVARCHAR', false, null, null);
		$this->addColumn('ACREDITACION_AZA', 'AcreditacionAza', 'INTEGER', false, null, null);
		$this->addColumn('ACREDITACION_ISO14001', 'AcreditacionIso14001', 'INTEGER', false, null, null);
		$this->addColumn('ACREDITACION_ISO9001', 'AcreditacionIso9001', 'INTEGER', false, null, null);
		$this->addColumn('ACREDITACION_OTRA', 'AcreditacionOtra', 'INTEGER', false, null, null);
		$this->addColumn('ASOCIACION_WAZA', 'AsociacionWaza', 'INTEGER', false, null, null);
		$this->addColumn('ASOCIACION_AZA', 'AsociacionAza', 'INTEGER', false, null, null);
		$this->addColumn('ASOCIACION_EAZA', 'AsociacionEaza', 'INTEGER', false, null, null);
		$this->addColumn('ASOCIACION_IZE', 'AsociacionIze', 'INTEGER', false, null, null);
		$this->addColumn('ASOCIACION_AMACZOA', 'AsociacionAmaczoa', 'INTEGER', false, null, null);
		$this->addColumn('ASOCIACION_ISIS', 'AsociacionIsis', 'INTEGER', false, null, null);
		$this->addColumn('ASOCIACION_OTRA', 'AsociacionOtra', 'INTEGER', false, null, null);
		$this->addColumn('MARCA_ANILLO', 'MarcaAnillo', 'INTEGER', false, null, null);
		$this->addColumn('MARCA_BANDA', 'MarcaBanda', 'INTEGER', false, null, null);
		$this->addColumn('MARCA_CALIENTE', 'MarcaCaliente', 'INTEGER', false, null, null);
		$this->addColumn('MARCA_FRIA', 'MarcaFria', 'INTEGER', false, null, null);
		$this->addColumn('MARCA_MICROCHIP', 'MarcaMicrochip', 'INTEGER', false, null, null);
		$this->addColumn('MARCA_NATURA', 'MarcaNatura', 'INTEGER', false, null, null);
		$this->addColumn('MARCA_PIQUETE', 'MarcaPiquete', 'INTEGER', false, null, null);
		$this->addColumn('MARCA_RAYA', 'MarcaRaya', 'INTEGER', false, null, null);
		$this->addColumn('MARCA_TATUAJE', 'MarcaTatuaje', 'INTEGER', false, null, null);
		$this->addColumn('MARCA_OTRA', 'MarcaOtra', 'INTEGER', false, null, null);
		$this->addColumn('VISITAS_ANUALES', 'VisitasAnuales', 'VARCHAR', false, 45, null);
		$this->addColumn('PROPIETARIO', 'Propietario', 'VARCHAR', false, 45, null);
		$this->addColumn('ADMINISTRADOR', 'Administrador', 'VARCHAR', false, 45, null);
		$this->addColumn('LUCRO', 'Lucro', 'INTEGER', false, null, null);
		$this->addColumn('OFRECE_ASESORIA', 'OfreceAsesoria', 'INTEGER', false, null, null);
		$this->addColumn('PERSONAL_PERMANENTE', 'PersonalPermanente', 'VARCHAR', false, 45, null);
		$this->addColumn('PERSONAL_TEMPORAL', 'PersonalTemporal', 'VARCHAR', false, 45, null);
		$this->addColumn('HORARIO_ATENCION', 'HorarioAtencion', 'LONGVARCHAR', false, null, null);
		$this->addColumn('OBJETIVO', 'Objetivo', 'LONGVARCHAR', false, null, null);
		$this->addColumn('SENALIZACION_PORCENTAJE', 'SenalizacionPorcentaje', 'VARCHAR', false, 100, null);
		$this->addColumn('ZOOLOGICO_CONTACTO', 'ZoologicoContacto', 'VARCHAR', false, 100, null);
		$this->addColumn('BOLETIN', 'Boletin', 'VARCHAR', false, 100, null);
		$this->addColumn('PROGRAMA_ENRIQUECIMIENTO', 'ProgramaEnriquecimiento', 'VARCHAR', false, 100, null);
		$this->addColumn('PROGRAMA_ENTRENAMIENTO', 'ProgramaEntrenamiento', 'VARCHAR', false, 100, null);
		$this->addColumn('PROGRAMA_MANEJO_AMBIENTAL', 'ProgramaManejoAmbiental', 'VARCHAR', false, 100, null);
		$this->addColumn('PROGRAMA_MEDICINA_PREVENTIVA', 'ProgramaMedicinaPreventiva', 'VARCHAR', false, 100, null);
		$this->addColumn('CONSULTA_EXTERNA_VETERINARIA', 'ConsultaExternaVeterinaria', 'VARCHAR', false, 100, null);
		$this->addColumn('SHOW', 'Show', 'VARCHAR', false, 100, null);
		$this->addColumn('DOCUMENTO_ESTRATEGICO', 'DocumentoEstrategico', 'VARCHAR', false, 100, null);
		$this->addColumn('PROYECTO_CONSERVACION_EXSITU', 'ProyectoConservacionExsitu', 'VARCHAR', false, 100, null);
		$this->addColumn('PROYECTO_CONSERVACION_INSITU', 'ProyectoConservacionInsitu', 'VARCHAR', false, 100, null);
		$this->addColumn('ASOCIACION_LISTA_ASOCIACIONES', 'AsociacionListaAsociaciones', 'VARCHAR', false, 100, null);
		$this->addColumn('ASOCIACION_LISTA_INSTITUCIONES', 'AsociacionListaInstituciones', 'VARCHAR', false, 100, null);
		$this->addColumn('ASOCIACION_APOYO_DESDE_ALPZA', 'AsociacionApoyoDesdeAlpza', 'VARCHAR', false, 100, null);
		$this->addColumn('ASOCIACION_APOYO_HACIA_ALPZA', 'AsociacionApoyoHaciaAlpza', 'VARCHAR', false, 100, null);
		$this->addColumn('ASOCIACION_ESTATUTOS', 'AsociacionEstatutos', 'VARCHAR', false, 100, null);
		$this->addColumn('ASOCIACION_ORGANIGRAMA', 'AsociacionOrganigrama', 'VARCHAR', false, 100, null);
		$this->addColumn('ASOCIACION_PANORAMA_PAIS', 'AsociacionPanoramaPais', 'VARCHAR', false, 100, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
		$this->addRelation('AlpzaMiembro', 'AlpzaMiembro', RelationMap::MANY_TO_ONE, array('alpza_miembro_id_alpza_miembro' => 'id_alpza_miembro', ), null, null);
	} // buildRelations()

	/**
	 *
	 * Gets the list of behaviors registered for this table
	 *
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // AlpzaMiembroAsociadosTableMap
