<?php

/**
 * Base class that represents a row from the 'alpza_miembro_general' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Nov 24 15:06:49 2012
 *
 * @package    lib.model.om
 */
abstract class BaseAlpzaMiembroGeneral extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AlpzaMiembroGeneralPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_alpza_miembro_general field.
	 * @var        int
	 */
	protected $id_alpza_miembro_general;

	/**
	 * The value for the id_alpza_miembro field.
	 * @var        int
	 */
	protected $id_alpza_miembro;

	/**
	 * The value for the nombre_formal field.
	 * @var        string
	 */
	protected $nombre_formal;

	/**
	 * The value for the sigla field.
	 * @var        string
	 */
	protected $sigla;

	/**
	 * The value for the tipo_institucion field.
	 * @var        string
	 */
	protected $tipo_institucion;

	/**
	 * The value for the numero_identificacion field.
	 * @var        string
	 */
	protected $numero_identificacion;

	/**
	 * The value for the ano_fundacion field.
	 * @var        string
	 */
	protected $ano_fundacion;

	/**
	 * The value for the ano_ingreso_alpza field.
	 * @var        string
	 */
	protected $ano_ingreso_alpza;

	/**
	 * The value for the director_nombre field.
	 * @var        string
	 */
	protected $director_nombre;

	/**
	 * The value for the director_email field.
	 * @var        string
	 */
	protected $director_email;

	/**
	 * The value for the delegado_nombre field.
	 * @var        string
	 */
	protected $delegado_nombre;

	/**
	 * The value for the delegado_apellido field.
	 * @var        string
	 */
	protected $delegado_apellido;

	/**
	 * The value for the delegado_cargo field.
	 * @var        string
	 */
	protected $delegado_cargo;

	/**
	 * The value for the delegado_profesion field.
	 * @var        string
	 */
	protected $delegado_profesion;

	/**
	 * The value for the delegado_email field.
	 * @var        string
	 */
	protected $delegado_email;

	/**
	 * The value for the logo field.
	 * @var        string
	 */
	protected $logo;

	/**
	 * The value for the direccion field.
	 * @var        string
	 */
	protected $direccion;

	/**
	 * The value for the ciudad_codigo_postal field.
	 * @var        string
	 */
	protected $ciudad_codigo_postal;

	/**
	 * The value for the pais field.
	 * @var        string
	 */
	protected $pais;

	/**
	 * The value for the telefono_cod_pais field.
	 * @var        string
	 */
	protected $telefono_cod_pais;

	/**
	 * The value for the telefono_cod_ciudad field.
	 * @var        string
	 */
	protected $telefono_cod_ciudad;

	/**
	 * The value for the telefono field.
	 * @var        string
	 */
	protected $telefono;

	/**
	 * The value for the fax field.
	 * @var        string
	 */
	protected $fax;

	/**
	 * The value for the celular field.
	 * @var        string
	 */
	protected $celular;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the sitio_web field.
	 * @var        string
	 */
	protected $sitio_web;

	/**
	 * The value for the descripcion field.
	 * @var        string
	 */
	protected $descripcion;

	/**
	 * The value for the mision field.
	 * @var        string
	 */
	protected $mision;

	/**
	 * The value for the vision field.
	 * @var        string
	 */
	protected $vision;

	/**
	 * The value for the objetivo field.
	 * @var        string
	 */
	protected $objetivo;

	/**
	 * The value for the asociacion_naturaleza_juridica field.
	 * @var        string
	 */
	protected $asociacion_naturaleza_juridica;

	/**
	 * The value for the profesional_nombre field.
	 * @var        string
	 */
	protected $profesional_nombre;

	/**
	 * The value for the profesional_apellido field.
	 * @var        string
	 */
	protected $profesional_apellido;

	/**
	 * The value for the profesional_profesion field.
	 * @var        string
	 */
	protected $profesional_profesion;

	/**
	 * The value for the profesional_trabajo field.
	 * @var        string
	 */
	protected $profesional_trabajo;

	/**
	 * The value for the profesional_cargo field.
	 * @var        string
	 */
	protected $profesional_cargo;

	/**
	 * The value for the profesional_otra_asociacion field.
	 * @var        string
	 */
	protected $profesional_otra_asociacion;

	/**
	 * @var        AlpzaMiembro
	 */
	protected $aAlpzaMiembro;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior

	const PEER = 'AlpzaMiembroGeneralPeer';

	/**
	 * Get the [id_alpza_miembro_general] column value.
	 *
	 * @return     int
	 */
	public function getIdAlpzaMiembroGeneral()
	{
		return $this->id_alpza_miembro_general;
	}

	/**
	 * Get the [id_alpza_miembro] column value.
	 *
	 * @return     int
	 */
	public function getIdAlpzaMiembro()
	{
		return $this->id_alpza_miembro;
	}

	/**
	 * Get the [nombre_formal] column value.
	 *
	 * @return     string
	 */
	public function getNombreFormal()
	{
		return $this->nombre_formal;
	}

	/**
	 * Get the [sigla] column value.
	 *
	 * @return     string
	 */
	public function getSigla()
	{
		return $this->sigla;
	}

	/**
	 * Get the [tipo_institucion] column value.
	 *
	 * @return     string
	 */
	public function getTipoInstitucion()
	{
		return $this->tipo_institucion;
	}

	/**
	 * Get the [numero_identificacion] column value.
	 *
	 * @return     string
	 */
	public function getNumeroIdentificacion()
	{
		return $this->numero_identificacion;
	}

	/**
	 * Get the [optionally formatted] temporal [ano_fundacion] column value.
	 *
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getAnoFundacion($format = 'Y-m-d')
	{
		if ($this->ano_fundacion === null) {
			return null;
		}


		if ($this->ano_fundacion === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->ano_fundacion);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->ano_fundacion, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [ano_ingreso_alpza] column value.
	 *
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getAnoIngresoAlpza($format = 'Y-m-d')
	{
		if ($this->ano_ingreso_alpza === null) {
			return null;
		}


		if ($this->ano_ingreso_alpza === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->ano_ingreso_alpza);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->ano_ingreso_alpza, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [director_nombre] column value.
	 *
	 * @return     string
	 */
	public function getDirectorNombre()
	{
		return $this->director_nombre;
	}

	/**
	 * Get the [director_email] column value.
	 *
	 * @return     string
	 */
	public function getDirectorEmail()
	{
		return $this->director_email;
	}

	/**
	 * Get the [delegado_nombre] column value.
	 *
	 * @return     string
	 */
	public function getDelegadoNombre()
	{
		return $this->delegado_nombre;
	}

	/**
	 * Get the [delegado_apellido] column value.
	 *
	 * @return     string
	 */
	public function getDelegadoApellido()
	{
		return $this->delegado_apellido;
	}

	/**
	 * Get the [delegado_cargo] column value.
	 *
	 * @return     string
	 */
	public function getDelegadoCargo()
	{
		return $this->delegado_cargo;
	}

	/**
	 * Get the [delegado_profesion] column value.
	 *
	 * @return     string
	 */
	public function getDelegadoProfesion()
	{
		return $this->delegado_profesion;
	}

	/**
	 * Get the [delegado_email] column value.
	 *
	 * @return     string
	 */
	public function getDelegadoEmail()
	{
		return $this->delegado_email;
	}

	/**
	 * Get the [logo] column value.
	 *
	 * @return     string
	 */
	public function getLogo()
	{
		return $this->logo;
	}

	/**
	 * Get the [direccion] column value.
	 *
	 * @return     string
	 */
	public function getDireccion()
	{
		return $this->direccion;
	}

	/**
	 * Get the [ciudad_codigo_postal] column value.
	 *
	 * @return     string
	 */
	public function getCiudadCodigoPostal()
	{
		return $this->ciudad_codigo_postal;
	}

	/**
	 * Get the [pais] column value.
	 *
	 * @return     string
	 */
	public function getPais()
	{
		return $this->pais;
	}

	/**
	 * Get the [telefono_cod_pais] column value.
	 *
	 * @return     string
	 */
	public function getTelefonoCodPais()
	{
		return $this->telefono_cod_pais;
	}

	/**
	 * Get the [telefono_cod_ciudad] column value.
	 *
	 * @return     string
	 */
	public function getTelefonoCodCiudad()
	{
		return $this->telefono_cod_ciudad;
	}

	/**
	 * Get the [telefono] column value.
	 *
	 * @return     string
	 */
	public function getTelefono()
	{
		return $this->telefono;
	}

	/**
	 * Get the [fax] column value.
	 *
	 * @return     string
	 */
	public function getFax()
	{
		return $this->fax;
	}

	/**
	 * Get the [celular] column value.
	 *
	 * @return     string
	 */
	public function getCelular()
	{
		return $this->celular;
	}

	/**
	 * Get the [email] column value.
	 *
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [sitio_web] column value.
	 *
	 * @return     string
	 */
	public function getSitioWeb()
	{
		return $this->sitio_web;
	}

	/**
	 * Get the [descripcion] column value.
	 *
	 * @return     string
	 */
	public function getDescripcion()
	{
		return $this->descripcion;
	}

	/**
	 * Get the [mision] column value.
	 *
	 * @return     string
	 */
	public function getMision()
	{
		return $this->mision;
	}

	/**
	 * Get the [vision] column value.
	 *
	 * @return     string
	 */
	public function getVision()
	{
		return $this->vision;
	}

	/**
	 * Get the [objetivo] column value.
	 *
	 * @return     string
	 */
	public function getObjetivo()
	{
		return $this->objetivo;
	}

	/**
	 * Get the [asociacion_naturaleza_juridica] column value.
	 *
	 * @return     string
	 */
	public function getAsociacionNaturalezaJuridica()
	{
		return $this->asociacion_naturaleza_juridica;
	}

	/**
	 * Get the [profesional_nombre] column value.
	 *
	 * @return     string
	 */
	public function getProfesionalNombre()
	{
		return $this->profesional_nombre;
	}

	/**
	 * Get the [profesional_apellido] column value.
	 *
	 * @return     string
	 */
	public function getProfesionalApellido()
	{
		return $this->profesional_apellido;
	}

	/**
	 * Get the [profesional_profesion] column value.
	 *
	 * @return     string
	 */
	public function getProfesionalProfesion()
	{
		return $this->profesional_profesion;
	}

	/**
	 * Get the [profesional_trabajo] column value.
	 *
	 * @return     string
	 */
	public function getProfesionalTrabajo()
	{
		return $this->profesional_trabajo;
	}

	/**
	 * Get the [profesional_cargo] column value.
	 *
	 * @return     string
	 */
	public function getProfesionalCargo()
	{
		return $this->profesional_cargo;
	}

	/**
	 * Get the [profesional_otra_asociacion] column value.
	 *
	 * @return     string
	 */
	public function getProfesionalOtraAsociacion()
	{
		return $this->profesional_otra_asociacion;
	}

	/**
	 * Set the value of [id_alpza_miembro_general] column.
	 *
	 * @param      int $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setIdAlpzaMiembroGeneral($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_alpza_miembro_general !== $v) {
			$this->id_alpza_miembro_general = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::ID_ALPZA_MIEMBRO_GENERAL;
		}

		return $this;
	} // setIdAlpzaMiembroGeneral()

	/**
	 * Set the value of [id_alpza_miembro] column.
	 *
	 * @param      int $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setIdAlpzaMiembro($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_alpza_miembro !== $v) {
			$this->id_alpza_miembro = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::ID_ALPZA_MIEMBRO;
		}

		if ($this->aAlpzaMiembro !== null && $this->aAlpzaMiembro->getIdAlpzaMiembro() !== $v) {
			$this->aAlpzaMiembro = null;
		}

		return $this;
	} // setIdAlpzaMiembro()

	/**
	 * Set the value of [nombre_formal] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setNombreFormal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->nombre_formal !== $v) {
			$this->nombre_formal = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::NOMBRE_FORMAL;
		}

		return $this;
	} // setNombreFormal()

	/**
	 * Set the value of [sigla] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setSigla($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->sigla !== $v) {
			$this->sigla = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::SIGLA;
		}

		return $this;
	} // setSigla()

	/**
	 * Set the value of [tipo_institucion] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setTipoInstitucion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->tipo_institucion !== $v) {
			$this->tipo_institucion = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::TIPO_INSTITUCION;
		}

		return $this;
	} // setTipoInstitucion()

	/**
	 * Set the value of [numero_identificacion] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setNumeroIdentificacion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->numero_identificacion !== $v) {
			$this->numero_identificacion = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::NUMERO_IDENTIFICACION;
		}

		return $this;
	} // setNumeroIdentificacion()

	/**
	 * Sets the value of [ano_fundacion] column to a normalized version of the date/time value specified.
	 *
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setAnoFundacion($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->ano_fundacion !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->ano_fundacion !== null && $tmpDt = new DateTime($this->ano_fundacion)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match
			)
			{
				$this->ano_fundacion = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::ANO_FUNDACION;
			}
		} // if either are not null

		return $this;
	} // setAnoFundacion()

	/**
	 * Sets the value of [ano_ingreso_alpza] column to a normalized version of the date/time value specified.
	 *
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setAnoIngresoAlpza($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->ano_ingreso_alpza !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->ano_ingreso_alpza !== null && $tmpDt = new DateTime($this->ano_ingreso_alpza)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match
			)
			{
				$this->ano_ingreso_alpza = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::ANO_INGRESO_ALPZA;
			}
		} // if either are not null

		return $this;
	} // setAnoIngresoAlpza()

	/**
	 * Set the value of [director_nombre] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setDirectorNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->director_nombre !== $v) {
			$this->director_nombre = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::DIRECTOR_NOMBRE;
		}

		return $this;
	} // setDirectorNombre()

	/**
	 * Set the value of [director_email] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setDirectorEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->director_email !== $v) {
			$this->director_email = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::DIRECTOR_EMAIL;
		}

		return $this;
	} // setDirectorEmail()

	/**
	 * Set the value of [delegado_nombre] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setDelegadoNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->delegado_nombre !== $v) {
			$this->delegado_nombre = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::DELEGADO_NOMBRE;
		}

		return $this;
	} // setDelegadoNombre()

	/**
	 * Set the value of [delegado_apellido] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setDelegadoApellido($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->delegado_apellido !== $v) {
			$this->delegado_apellido = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::DELEGADO_APELLIDO;
		}

		return $this;
	} // setDelegadoApellido()

	/**
	 * Set the value of [delegado_cargo] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setDelegadoCargo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->delegado_cargo !== $v) {
			$this->delegado_cargo = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::DELEGADO_CARGO;
		}

		return $this;
	} // setDelegadoCargo()

	/**
	 * Set the value of [delegado_profesion] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setDelegadoProfesion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->delegado_profesion !== $v) {
			$this->delegado_profesion = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::DELEGADO_PROFESION;
		}

		return $this;
	} // setDelegadoProfesion()

	/**
	 * Set the value of [delegado_email] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setDelegadoEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->delegado_email !== $v) {
			$this->delegado_email = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::DELEGADO_EMAIL;
		}

		return $this;
	} // setDelegadoEmail()

	/**
	 * Set the value of [logo] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setLogo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->logo !== $v) {
			$this->logo = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::LOGO;
		}

		return $this;
	} // setLogo()

	/**
	 * Set the value of [direccion] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setDireccion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->direccion !== $v) {
			$this->direccion = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::DIRECCION;
		}

		return $this;
	} // setDireccion()

	/**
	 * Set the value of [ciudad_codigo_postal] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setCiudadCodigoPostal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ciudad_codigo_postal !== $v) {
			$this->ciudad_codigo_postal = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::CIUDAD_CODIGO_POSTAL;
		}

		return $this;
	} // setCiudadCodigoPostal()

	/**
	 * Set the value of [pais] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setPais($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pais !== $v) {
			$this->pais = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::PAIS;
		}

		return $this;
	} // setPais()

	/**
	 * Set the value of [telefono_cod_pais] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setTelefonoCodPais($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telefono_cod_pais !== $v) {
			$this->telefono_cod_pais = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::TELEFONO_COD_PAIS;
		}

		return $this;
	} // setTelefonoCodPais()

	/**
	 * Set the value of [telefono_cod_ciudad] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setTelefonoCodCiudad($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telefono_cod_ciudad !== $v) {
			$this->telefono_cod_ciudad = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::TELEFONO_COD_CIUDAD;
		}

		return $this;
	} // setTelefonoCodCiudad()

	/**
	 * Set the value of [telefono] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setTelefono($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->telefono !== $v) {
			$this->telefono = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::TELEFONO;
		}

		return $this;
	} // setTelefono()

	/**
	 * Set the value of [fax] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setFax($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fax !== $v) {
			$this->fax = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::FAX;
		}

		return $this;
	} // setFax()

	/**
	 * Set the value of [celular] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setCelular($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->celular !== $v) {
			$this->celular = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::CELULAR;
		}

		return $this;
	} // setCelular()

	/**
	 * Set the value of [email] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [sitio_web] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setSitioWeb($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->sitio_web !== $v) {
			$this->sitio_web = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::SITIO_WEB;
		}

		return $this;
	} // setSitioWeb()

	/**
	 * Set the value of [descripcion] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->descripcion !== $v) {
			$this->descripcion = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::DESCRIPCION;
		}

		return $this;
	} // setDescripcion()

	/**
	 * Set the value of [mision] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setMision($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mision !== $v) {
			$this->mision = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::MISION;
		}

		return $this;
	} // setMision()

	/**
	 * Set the value of [vision] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setVision($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->vision !== $v) {
			$this->vision = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::VISION;
		}

		return $this;
	} // setVision()

	/**
	 * Set the value of [objetivo] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setObjetivo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->objetivo !== $v) {
			$this->objetivo = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::OBJETIVO;
		}

		return $this;
	} // setObjetivo()

	/**
	 * Set the value of [asociacion_naturaleza_juridica] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setAsociacionNaturalezaJuridica($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->asociacion_naturaleza_juridica !== $v) {
			$this->asociacion_naturaleza_juridica = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::ASOCIACION_NATURALEZA_JURIDICA;
		}

		return $this;
	} // setAsociacionNaturalezaJuridica()

	/**
	 * Set the value of [profesional_nombre] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setProfesionalNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->profesional_nombre !== $v) {
			$this->profesional_nombre = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::PROFESIONAL_NOMBRE;
		}

		return $this;
	} // setProfesionalNombre()

	/**
	 * Set the value of [profesional_apellido] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setProfesionalApellido($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->profesional_apellido !== $v) {
			$this->profesional_apellido = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::PROFESIONAL_APELLIDO;
		}

		return $this;
	} // setProfesionalApellido()

	/**
	 * Set the value of [profesional_profesion] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setProfesionalProfesion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->profesional_profesion !== $v) {
			$this->profesional_profesion = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::PROFESIONAL_PROFESION;
		}

		return $this;
	} // setProfesionalProfesion()

	/**
	 * Set the value of [profesional_trabajo] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setProfesionalTrabajo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->profesional_trabajo !== $v) {
			$this->profesional_trabajo = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::PROFESIONAL_TRABAJO;
		}

		return $this;
	} // setProfesionalTrabajo()

	/**
	 * Set the value of [profesional_cargo] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setProfesionalCargo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->profesional_cargo !== $v) {
			$this->profesional_cargo = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::PROFESIONAL_CARGO;
		}

		return $this;
	} // setProfesionalCargo()

	/**
	 * Set the value of [profesional_otra_asociacion] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 */
	public function setProfesionalOtraAsociacion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->profesional_otra_asociacion !== $v) {
			$this->profesional_otra_asociacion = $v;
			$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::PROFESIONAL_OTRA_ASOCIACION;
		}

		return $this;
	} // setProfesionalOtraAsociacion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_alpza_miembro_general = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_alpza_miembro = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->nombre_formal = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->sigla = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->tipo_institucion = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->numero_identificacion = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->ano_fundacion = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->ano_ingreso_alpza = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->director_nombre = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->director_email = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->delegado_nombre = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->delegado_apellido = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->delegado_cargo = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->delegado_profesion = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->delegado_email = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->logo = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->direccion = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->ciudad_codigo_postal = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->pais = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->telefono_cod_pais = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->telefono_cod_ciudad = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
			$this->telefono = ($row[$startcol + 21] !== null) ? (string) $row[$startcol + 21] : null;
			$this->fax = ($row[$startcol + 22] !== null) ? (string) $row[$startcol + 22] : null;
			$this->celular = ($row[$startcol + 23] !== null) ? (string) $row[$startcol + 23] : null;
			$this->email = ($row[$startcol + 24] !== null) ? (string) $row[$startcol + 24] : null;
			$this->sitio_web = ($row[$startcol + 25] !== null) ? (string) $row[$startcol + 25] : null;
			$this->descripcion = ($row[$startcol + 26] !== null) ? (string) $row[$startcol + 26] : null;
			$this->mision = ($row[$startcol + 27] !== null) ? (string) $row[$startcol + 27] : null;
			$this->vision = ($row[$startcol + 28] !== null) ? (string) $row[$startcol + 28] : null;
			$this->objetivo = ($row[$startcol + 29] !== null) ? (string) $row[$startcol + 29] : null;
			$this->asociacion_naturaleza_juridica = ($row[$startcol + 30] !== null) ? (string) $row[$startcol + 30] : null;
			$this->profesional_nombre = ($row[$startcol + 31] !== null) ? (string) $row[$startcol + 31] : null;
			$this->profesional_apellido = ($row[$startcol + 32] !== null) ? (string) $row[$startcol + 32] : null;
			$this->profesional_profesion = ($row[$startcol + 33] !== null) ? (string) $row[$startcol + 33] : null;
			$this->profesional_trabajo = ($row[$startcol + 34] !== null) ? (string) $row[$startcol + 34] : null;
			$this->profesional_cargo = ($row[$startcol + 35] !== null) ? (string) $row[$startcol + 35] : null;
			$this->profesional_otra_asociacion = ($row[$startcol + 36] !== null) ? (string) $row[$startcol + 36] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 37; // 37 = AlpzaMiembroGeneralPeer::NUM_COLUMNS - AlpzaMiembroGeneralPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating AlpzaMiembroGeneral object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aAlpzaMiembro !== null && $this->id_alpza_miembro !== $this->aAlpzaMiembro->getIdAlpzaMiembro()) {
			$this->aAlpzaMiembro = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroGeneralPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AlpzaMiembroGeneralPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aAlpzaMiembro = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroGeneralPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAlpzaMiembroGeneral:delete:pre') as $callable)
			{
				if (call_user_func($callable, $this, $con))
				{
					$con->commit();
						
					return;
				}
			}

			if ($ret) {
				AlpzaMiembroGeneralPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAlpzaMiembroGeneral:delete:post') as $callable)
				{
					call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroGeneralPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAlpzaMiembroGeneral:save:pre') as $callable)
			{
				if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
				{
					$con->commit();
						
					return $affectedRows;
				}
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAlpzaMiembroGeneral:save:post') as $callable)
				{
					call_user_func($callable, $this, $con, $affectedRows);
				}

				AlpzaMiembroGeneralPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAlpzaMiembro !== null) {
				if ($this->aAlpzaMiembro->isModified() || $this->aAlpzaMiembro->isNew()) {
					$affectedRows += $this->aAlpzaMiembro->save($con);
				}
				$this->setAlpzaMiembro($this->aAlpzaMiembro);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AlpzaMiembroGeneralPeer::ID_ALPZA_MIEMBRO_GENERAL;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AlpzaMiembroGeneralPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
					// should always be true here (even though technically
					// BasePeer::doInsert() can insert multiple rows).

					$this->setIdAlpzaMiembroGeneral($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AlpzaMiembroGeneralPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAlpzaMiembro !== null) {
				if (!$this->aAlpzaMiembro->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAlpzaMiembro->getValidationFailures());
				}
			}


			if (($retval = AlpzaMiembroGeneralPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AlpzaMiembroGeneralPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdAlpzaMiembroGeneral();
				break;
			case 1:
				return $this->getIdAlpzaMiembro();
				break;
			case 2:
				return $this->getNombreFormal();
				break;
			case 3:
				return $this->getSigla();
				break;
			case 4:
				return $this->getTipoInstitucion();
				break;
			case 5:
				return $this->getNumeroIdentificacion();
				break;
			case 6:
				return $this->getAnoFundacion();
				break;
			case 7:
				return $this->getAnoIngresoAlpza();
				break;
			case 8:
				return $this->getDirectorNombre();
				break;
			case 9:
				return $this->getDirectorEmail();
				break;
			case 10:
				return $this->getDelegadoNombre();
				break;
			case 11:
				return $this->getDelegadoApellido();
				break;
			case 12:
				return $this->getDelegadoCargo();
				break;
			case 13:
				return $this->getDelegadoProfesion();
				break;
			case 14:
				return $this->getDelegadoEmail();
				break;
			case 15:
				return $this->getLogo();
				break;
			case 16:
				return $this->getDireccion();
				break;
			case 17:
				return $this->getCiudadCodigoPostal();
				break;
			case 18:
				return $this->getPais();
				break;
			case 19:
				return $this->getTelefonoCodPais();
				break;
			case 20:
				return $this->getTelefonoCodCiudad();
				break;
			case 21:
				return $this->getTelefono();
				break;
			case 22:
				return $this->getFax();
				break;
			case 23:
				return $this->getCelular();
				break;
			case 24:
				return $this->getEmail();
				break;
			case 25:
				return $this->getSitioWeb();
				break;
			case 26:
				return $this->getDescripcion();
				break;
			case 27:
				return $this->getMision();
				break;
			case 28:
				return $this->getVision();
				break;
			case 29:
				return $this->getObjetivo();
				break;
			case 30:
				return $this->getAsociacionNaturalezaJuridica();
				break;
			case 31:
				return $this->getProfesionalNombre();
				break;
			case 32:
				return $this->getProfesionalApellido();
				break;
			case 33:
				return $this->getProfesionalProfesion();
				break;
			case 34:
				return $this->getProfesionalTrabajo();
				break;
			case 35:
				return $this->getProfesionalCargo();
				break;
			case 36:
				return $this->getProfesionalOtraAsociacion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AlpzaMiembroGeneralPeer::getFieldNames($keyType);
		$result = array(
		$keys[0] => $this->getIdAlpzaMiembroGeneral(),
		$keys[1] => $this->getIdAlpzaMiembro(),
		$keys[2] => $this->getNombreFormal(),
		$keys[3] => $this->getSigla(),
		$keys[4] => $this->getTipoInstitucion(),
		$keys[5] => $this->getNumeroIdentificacion(),
		$keys[6] => $this->getAnoFundacion(),
		$keys[7] => $this->getAnoIngresoAlpza(),
		$keys[8] => $this->getDirectorNombre(),
		$keys[9] => $this->getDirectorEmail(),
		$keys[10] => $this->getDelegadoNombre(),
		$keys[11] => $this->getDelegadoApellido(),
		$keys[12] => $this->getDelegadoCargo(),
		$keys[13] => $this->getDelegadoProfesion(),
		$keys[14] => $this->getDelegadoEmail(),
		$keys[15] => $this->getLogo(),
		$keys[16] => $this->getDireccion(),
		$keys[17] => $this->getCiudadCodigoPostal(),
		$keys[18] => $this->getPais(),
		$keys[19] => $this->getTelefonoCodPais(),
		$keys[20] => $this->getTelefonoCodCiudad(),
		$keys[21] => $this->getTelefono(),
		$keys[22] => $this->getFax(),
		$keys[23] => $this->getCelular(),
		$keys[24] => $this->getEmail(),
		$keys[25] => $this->getSitioWeb(),
		$keys[26] => $this->getDescripcion(),
		$keys[27] => $this->getMision(),
		$keys[28] => $this->getVision(),
		$keys[29] => $this->getObjetivo(),
		$keys[30] => $this->getAsociacionNaturalezaJuridica(),
		$keys[31] => $this->getProfesionalNombre(),
		$keys[32] => $this->getProfesionalApellido(),
		$keys[33] => $this->getProfesionalProfesion(),
		$keys[34] => $this->getProfesionalTrabajo(),
		$keys[35] => $this->getProfesionalCargo(),
		$keys[36] => $this->getProfesionalOtraAsociacion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AlpzaMiembroGeneralPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdAlpzaMiembroGeneral($value);
				break;
			case 1:
				$this->setIdAlpzaMiembro($value);
				break;
			case 2:
				$this->setNombreFormal($value);
				break;
			case 3:
				$this->setSigla($value);
				break;
			case 4:
				$this->setTipoInstitucion($value);
				break;
			case 5:
				$this->setNumeroIdentificacion($value);
				break;
			case 6:
				$this->setAnoFundacion($value);
				break;
			case 7:
				$this->setAnoIngresoAlpza($value);
				break;
			case 8:
				$this->setDirectorNombre($value);
				break;
			case 9:
				$this->setDirectorEmail($value);
				break;
			case 10:
				$this->setDelegadoNombre($value);
				break;
			case 11:
				$this->setDelegadoApellido($value);
				break;
			case 12:
				$this->setDelegadoCargo($value);
				break;
			case 13:
				$this->setDelegadoProfesion($value);
				break;
			case 14:
				$this->setDelegadoEmail($value);
				break;
			case 15:
				$this->setLogo($value);
				break;
			case 16:
				$this->setDireccion($value);
				break;
			case 17:
				$this->setCiudadCodigoPostal($value);
				break;
			case 18:
				$this->setPais($value);
				break;
			case 19:
				$this->setTelefonoCodPais($value);
				break;
			case 20:
				$this->setTelefonoCodCiudad($value);
				break;
			case 21:
				$this->setTelefono($value);
				break;
			case 22:
				$this->setFax($value);
				break;
			case 23:
				$this->setCelular($value);
				break;
			case 24:
				$this->setEmail($value);
				break;
			case 25:
				$this->setSitioWeb($value);
				break;
			case 26:
				$this->setDescripcion($value);
				break;
			case 27:
				$this->setMision($value);
				break;
			case 28:
				$this->setVision($value);
				break;
			case 29:
				$this->setObjetivo($value);
				break;
			case 30:
				$this->setAsociacionNaturalezaJuridica($value);
				break;
			case 31:
				$this->setProfesionalNombre($value);
				break;
			case 32:
				$this->setProfesionalApellido($value);
				break;
			case 33:
				$this->setProfesionalProfesion($value);
				break;
			case 34:
				$this->setProfesionalTrabajo($value);
				break;
			case 35:
				$this->setProfesionalCargo($value);
				break;
			case 36:
				$this->setProfesionalOtraAsociacion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AlpzaMiembroGeneralPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdAlpzaMiembroGeneral($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdAlpzaMiembro($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setNombreFormal($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setSigla($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setTipoInstitucion($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setNumeroIdentificacion($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setAnoFundacion($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setAnoIngresoAlpza($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDirectorNombre($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setDirectorEmail($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setDelegadoNombre($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setDelegadoApellido($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setDelegadoCargo($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setDelegadoProfesion($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setDelegadoEmail($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setLogo($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setDireccion($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setCiudadCodigoPostal($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setPais($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setTelefonoCodPais($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setTelefonoCodCiudad($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setTelefono($arr[$keys[21]]);
		if (array_key_exists($keys[22], $arr)) $this->setFax($arr[$keys[22]]);
		if (array_key_exists($keys[23], $arr)) $this->setCelular($arr[$keys[23]]);
		if (array_key_exists($keys[24], $arr)) $this->setEmail($arr[$keys[24]]);
		if (array_key_exists($keys[25], $arr)) $this->setSitioWeb($arr[$keys[25]]);
		if (array_key_exists($keys[26], $arr)) $this->setDescripcion($arr[$keys[26]]);
		if (array_key_exists($keys[27], $arr)) $this->setMision($arr[$keys[27]]);
		if (array_key_exists($keys[28], $arr)) $this->setVision($arr[$keys[28]]);
		if (array_key_exists($keys[29], $arr)) $this->setObjetivo($arr[$keys[29]]);
		if (array_key_exists($keys[30], $arr)) $this->setAsociacionNaturalezaJuridica($arr[$keys[30]]);
		if (array_key_exists($keys[31], $arr)) $this->setProfesionalNombre($arr[$keys[31]]);
		if (array_key_exists($keys[32], $arr)) $this->setProfesionalApellido($arr[$keys[32]]);
		if (array_key_exists($keys[33], $arr)) $this->setProfesionalProfesion($arr[$keys[33]]);
		if (array_key_exists($keys[34], $arr)) $this->setProfesionalTrabajo($arr[$keys[34]]);
		if (array_key_exists($keys[35], $arr)) $this->setProfesionalCargo($arr[$keys[35]]);
		if (array_key_exists($keys[36], $arr)) $this->setProfesionalOtraAsociacion($arr[$keys[36]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AlpzaMiembroGeneralPeer::DATABASE_NAME);

		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::ID_ALPZA_MIEMBRO_GENERAL)) $criteria->add(AlpzaMiembroGeneralPeer::ID_ALPZA_MIEMBRO_GENERAL, $this->id_alpza_miembro_general);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::ID_ALPZA_MIEMBRO)) $criteria->add(AlpzaMiembroGeneralPeer::ID_ALPZA_MIEMBRO, $this->id_alpza_miembro);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::NOMBRE_FORMAL)) $criteria->add(AlpzaMiembroGeneralPeer::NOMBRE_FORMAL, $this->nombre_formal);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::SIGLA)) $criteria->add(AlpzaMiembroGeneralPeer::SIGLA, $this->sigla);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::TIPO_INSTITUCION)) $criteria->add(AlpzaMiembroGeneralPeer::TIPO_INSTITUCION, $this->tipo_institucion);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::NUMERO_IDENTIFICACION)) $criteria->add(AlpzaMiembroGeneralPeer::NUMERO_IDENTIFICACION, $this->numero_identificacion);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::ANO_FUNDACION)) $criteria->add(AlpzaMiembroGeneralPeer::ANO_FUNDACION, $this->ano_fundacion);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::ANO_INGRESO_ALPZA)) $criteria->add(AlpzaMiembroGeneralPeer::ANO_INGRESO_ALPZA, $this->ano_ingreso_alpza);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::DIRECTOR_NOMBRE)) $criteria->add(AlpzaMiembroGeneralPeer::DIRECTOR_NOMBRE, $this->director_nombre);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::DIRECTOR_EMAIL)) $criteria->add(AlpzaMiembroGeneralPeer::DIRECTOR_EMAIL, $this->director_email);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::DELEGADO_NOMBRE)) $criteria->add(AlpzaMiembroGeneralPeer::DELEGADO_NOMBRE, $this->delegado_nombre);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::DELEGADO_APELLIDO)) $criteria->add(AlpzaMiembroGeneralPeer::DELEGADO_APELLIDO, $this->delegado_apellido);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::DELEGADO_CARGO)) $criteria->add(AlpzaMiembroGeneralPeer::DELEGADO_CARGO, $this->delegado_cargo);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::DELEGADO_PROFESION)) $criteria->add(AlpzaMiembroGeneralPeer::DELEGADO_PROFESION, $this->delegado_profesion);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::DELEGADO_EMAIL)) $criteria->add(AlpzaMiembroGeneralPeer::DELEGADO_EMAIL, $this->delegado_email);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::LOGO)) $criteria->add(AlpzaMiembroGeneralPeer::LOGO, $this->logo);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::DIRECCION)) $criteria->add(AlpzaMiembroGeneralPeer::DIRECCION, $this->direccion);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::CIUDAD_CODIGO_POSTAL)) $criteria->add(AlpzaMiembroGeneralPeer::CIUDAD_CODIGO_POSTAL, $this->ciudad_codigo_postal);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::PAIS)) $criteria->add(AlpzaMiembroGeneralPeer::PAIS, $this->pais);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::TELEFONO_COD_PAIS)) $criteria->add(AlpzaMiembroGeneralPeer::TELEFONO_COD_PAIS, $this->telefono_cod_pais);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::TELEFONO_COD_CIUDAD)) $criteria->add(AlpzaMiembroGeneralPeer::TELEFONO_COD_CIUDAD, $this->telefono_cod_ciudad);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::TELEFONO)) $criteria->add(AlpzaMiembroGeneralPeer::TELEFONO, $this->telefono);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::FAX)) $criteria->add(AlpzaMiembroGeneralPeer::FAX, $this->fax);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::CELULAR)) $criteria->add(AlpzaMiembroGeneralPeer::CELULAR, $this->celular);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::EMAIL)) $criteria->add(AlpzaMiembroGeneralPeer::EMAIL, $this->email);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::SITIO_WEB)) $criteria->add(AlpzaMiembroGeneralPeer::SITIO_WEB, $this->sitio_web);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::DESCRIPCION)) $criteria->add(AlpzaMiembroGeneralPeer::DESCRIPCION, $this->descripcion);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::MISION)) $criteria->add(AlpzaMiembroGeneralPeer::MISION, $this->mision);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::VISION)) $criteria->add(AlpzaMiembroGeneralPeer::VISION, $this->vision);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::OBJETIVO)) $criteria->add(AlpzaMiembroGeneralPeer::OBJETIVO, $this->objetivo);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::ASOCIACION_NATURALEZA_JURIDICA)) $criteria->add(AlpzaMiembroGeneralPeer::ASOCIACION_NATURALEZA_JURIDICA, $this->asociacion_naturaleza_juridica);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::PROFESIONAL_NOMBRE)) $criteria->add(AlpzaMiembroGeneralPeer::PROFESIONAL_NOMBRE, $this->profesional_nombre);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::PROFESIONAL_APELLIDO)) $criteria->add(AlpzaMiembroGeneralPeer::PROFESIONAL_APELLIDO, $this->profesional_apellido);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::PROFESIONAL_PROFESION)) $criteria->add(AlpzaMiembroGeneralPeer::PROFESIONAL_PROFESION, $this->profesional_profesion);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::PROFESIONAL_TRABAJO)) $criteria->add(AlpzaMiembroGeneralPeer::PROFESIONAL_TRABAJO, $this->profesional_trabajo);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::PROFESIONAL_CARGO)) $criteria->add(AlpzaMiembroGeneralPeer::PROFESIONAL_CARGO, $this->profesional_cargo);
		if ($this->isColumnModified(AlpzaMiembroGeneralPeer::PROFESIONAL_OTRA_ASOCIACION)) $criteria->add(AlpzaMiembroGeneralPeer::PROFESIONAL_OTRA_ASOCIACION, $this->profesional_otra_asociacion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AlpzaMiembroGeneralPeer::DATABASE_NAME);

		$criteria->add(AlpzaMiembroGeneralPeer::ID_ALPZA_MIEMBRO_GENERAL, $this->id_alpza_miembro_general);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdAlpzaMiembroGeneral();
	}

	/**
	 * Generic method to set the primary key (id_alpza_miembro_general column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdAlpzaMiembroGeneral($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of AlpzaMiembroGeneral (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdAlpzaMiembro($this->id_alpza_miembro);

		$copyObj->setNombreFormal($this->nombre_formal);

		$copyObj->setSigla($this->sigla);

		$copyObj->setTipoInstitucion($this->tipo_institucion);

		$copyObj->setNumeroIdentificacion($this->numero_identificacion);

		$copyObj->setAnoFundacion($this->ano_fundacion);

		$copyObj->setAnoIngresoAlpza($this->ano_ingreso_alpza);

		$copyObj->setDirectorNombre($this->director_nombre);

		$copyObj->setDirectorEmail($this->director_email);

		$copyObj->setDelegadoNombre($this->delegado_nombre);

		$copyObj->setDelegadoApellido($this->delegado_apellido);

		$copyObj->setDelegadoCargo($this->delegado_cargo);

		$copyObj->setDelegadoProfesion($this->delegado_profesion);

		$copyObj->setDelegadoEmail($this->delegado_email);

		$copyObj->setLogo($this->logo);

		$copyObj->setDireccion($this->direccion);

		$copyObj->setCiudadCodigoPostal($this->ciudad_codigo_postal);

		$copyObj->setPais($this->pais);

		$copyObj->setTelefonoCodPais($this->telefono_cod_pais);

		$copyObj->setTelefonoCodCiudad($this->telefono_cod_ciudad);

		$copyObj->setTelefono($this->telefono);

		$copyObj->setFax($this->fax);

		$copyObj->setCelular($this->celular);

		$copyObj->setEmail($this->email);

		$copyObj->setSitioWeb($this->sitio_web);

		$copyObj->setDescripcion($this->descripcion);

		$copyObj->setMision($this->mision);

		$copyObj->setVision($this->vision);

		$copyObj->setObjetivo($this->objetivo);

		$copyObj->setAsociacionNaturalezaJuridica($this->asociacion_naturaleza_juridica);

		$copyObj->setProfesionalNombre($this->profesional_nombre);

		$copyObj->setProfesionalApellido($this->profesional_apellido);

		$copyObj->setProfesionalProfesion($this->profesional_profesion);

		$copyObj->setProfesionalTrabajo($this->profesional_trabajo);

		$copyObj->setProfesionalCargo($this->profesional_cargo);

		$copyObj->setProfesionalOtraAsociacion($this->profesional_otra_asociacion);


		$copyObj->setNew(true);

		$copyObj->setIdAlpzaMiembroGeneral(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     AlpzaMiembroGeneral Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AlpzaMiembroGeneralPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AlpzaMiembroGeneralPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a AlpzaMiembro object.
	 *
	 * @param      AlpzaMiembro $v
	 * @return     AlpzaMiembroGeneral The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAlpzaMiembro(AlpzaMiembro $v = null)
	{
		if ($v === null) {
			$this->setIdAlpzaMiembro(NULL);
		} else {
			$this->setIdAlpzaMiembro($v->getIdAlpzaMiembro());
		}

		$this->aAlpzaMiembro = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the AlpzaMiembro object, it will not be re-added.
		if ($v !== null) {
			$v->addAlpzaMiembroGeneral($this);
		}

		return $this;
	}


	/**
	 * Get the associated AlpzaMiembro object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     AlpzaMiembro The associated AlpzaMiembro object.
	 * @throws     PropelException
	 */
	public function getAlpzaMiembro(PropelPDO $con = null)
	{
		if ($this->aAlpzaMiembro === null && ($this->id_alpza_miembro !== null)) {
			$this->aAlpzaMiembro = AlpzaMiembroPeer::retrieveByPk($this->id_alpza_miembro);
			/* The following can be used additionally to
			 guarantee the related object contains a reference
			 to this object.  This level of coupling may, however, be
			 undesirable since it could result in an only partially populated collection
			 in the referenced object.
			 $this->aAlpzaMiembro->addAlpzaMiembroGenerals($this);
			 */
		}
		return $this->aAlpzaMiembro;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

		$this->aAlpzaMiembro = null;
	}

	// symfony_behaviors behavior

	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
		if (!$callable = sfMixer::getCallable('BaseAlpzaMiembroGeneral:'.$method))
		{
			throw new sfException(sprintf('Call to undefined method BaseAlpzaMiembroGeneral::%s', $method));
		}

		array_unshift($arguments, $this);

		return call_user_func_array($callable, $arguments);
	}

} // BaseAlpzaMiembroGeneral
