<?php

/**
 * Base static class for performing query and update operations on the 'alpza_miembro_nacionales' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Nov 24 15:15:37 2012
 *
 * @package    lib.model.om
 */
abstract class BaseAlpzaMiembroNacionalesPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'alpza_miembro_nacionales';

	/** the related Propel class for this table */
	const OM_CLASS = 'AlpzaMiembroNacionales';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.AlpzaMiembroNacionales';

	/** the related TableMap class for this table */
	const TM_CLASS = 'AlpzaMiembroNacionalesTableMap';

	/** The total number of columns. */
	const NUM_COLUMNS = 46;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID_ALPZA_MIEMBRO_NACIONALES field */
	const ID_ALPZA_MIEMBRO_NACIONALES = 'alpza_miembro_nacionales.ID_ALPZA_MIEMBRO_NACIONALES';

	/** the column name for the ALPZA_MIEMBRO_ID_ALPZA_MIEMBRO field */
	const ALPZA_MIEMBRO_ID_ALPZA_MIEMBRO = 'alpza_miembro_nacionales.ALPZA_MIEMBRO_ID_ALPZA_MIEMBRO';

	/** the column name for the NOMBRE_FORMAL field */
	const NOMBRE_FORMAL = 'alpza_miembro_nacionales.NOMBRE_FORMAL';

	/** the column name for the SIGLA field */
	const SIGLA = 'alpza_miembro_nacionales.SIGLA';

	/** the column name for the NUMERO_IDENTIFICACION field */
	const NUMERO_IDENTIFICACION = 'alpza_miembro_nacionales.NUMERO_IDENTIFICACION';

	/** the column name for the ANO_FUNDACION field */
	const ANO_FUNDACION = 'alpza_miembro_nacionales.ANO_FUNDACION';

	/** the column name for the ANO_INGRESO_ALPZA field */
	const ANO_INGRESO_ALPZA = 'alpza_miembro_nacionales.ANO_INGRESO_ALPZA';

	/** the column name for the DIRECTOR_NOMBRE field */
	const DIRECTOR_NOMBRE = 'alpza_miembro_nacionales.DIRECTOR_NOMBRE';

	/** the column name for the DIRECTOR_EMAIL field */
	const DIRECTOR_EMAIL = 'alpza_miembro_nacionales.DIRECTOR_EMAIL';

	/** the column name for the PERSONAL_PERMANENTE field */
	const PERSONAL_PERMANENTE = 'alpza_miembro_nacionales.PERSONAL_PERMANENTE';

	/** the column name for the PERSONAL_TEMPORAL field */
	const PERSONAL_TEMPORAL = 'alpza_miembro_nacionales.PERSONAL_TEMPORAL';

	/** the column name for the DELEGADO_NOMBRE field */
	const DELEGADO_NOMBRE = 'alpza_miembro_nacionales.DELEGADO_NOMBRE';

	/** the column name for the DELEGADO_APELLIDO field */
	const DELEGADO_APELLIDO = 'alpza_miembro_nacionales.DELEGADO_APELLIDO';

	/** the column name for the DELEGADO_PROFESION field */
	const DELEGADO_PROFESION = 'alpza_miembro_nacionales.DELEGADO_PROFESION';

	/** the column name for the DELEGADO_CARGO field */
	const DELEGADO_CARGO = 'alpza_miembro_nacionales.DELEGADO_CARGO';

	/** the column name for the DELEGADO_EMAIL field */
	const DELEGADO_EMAIL = 'alpza_miembro_nacionales.DELEGADO_EMAIL';

	/** the column name for the LOGO field */
	const LOGO = 'alpza_miembro_nacionales.LOGO';

	/** the column name for the DIRECCION field */
	const DIRECCION = 'alpza_miembro_nacionales.DIRECCION';

	/** the column name for the CODIGO_POSTAL field */
	const CODIGO_POSTAL = 'alpza_miembro_nacionales.CODIGO_POSTAL';

	/** the column name for the PAIS field */
	const PAIS = 'alpza_miembro_nacionales.PAIS';

	/** the column name for the TELEFONO_COD_CIUDAD field */
	const TELEFONO_COD_CIUDAD = 'alpza_miembro_nacionales.TELEFONO_COD_CIUDAD';

	/** the column name for the TELEFONO_COD_PAIS field */
	const TELEFONO_COD_PAIS = 'alpza_miembro_nacionales.TELEFONO_COD_PAIS';

	/** the column name for the TELEFONO field */
	const TELEFONO = 'alpza_miembro_nacionales.TELEFONO';

	/** the column name for the FAX field */
	const FAX = 'alpza_miembro_nacionales.FAX';

	/** the column name for the CELULAR field */
	const CELULAR = 'alpza_miembro_nacionales.CELULAR';

	/** the column name for the EMAIL field */
	const EMAIL = 'alpza_miembro_nacionales.EMAIL';

	/** the column name for the SITIO_WEB field */
	const SITIO_WEB = 'alpza_miembro_nacionales.SITIO_WEB';

	/** the column name for the NATURALEZA_JURIDICA_PUBLICA field */
	const NATURALEZA_JURIDICA_PUBLICA = 'alpza_miembro_nacionales.NATURALEZA_JURIDICA_PUBLICA';

	/** the column name for the NATURALEZA_JURIDICA_PRIVADA field */
	const NATURALEZA_JURIDICA_PRIVADA = 'alpza_miembro_nacionales.NATURALEZA_JURIDICA_PRIVADA';

	/** the column name for the NATURALEZA_JURIDICA_MIXTA field */
	const NATURALEZA_JURIDICA_MIXTA = 'alpza_miembro_nacionales.NATURALEZA_JURIDICA_MIXTA';

	/** the column name for the PROPIETARIO field */
	const PROPIETARIO = 'alpza_miembro_nacionales.PROPIETARIO';

	/** the column name for the LUCRO field */
	const LUCRO = 'alpza_miembro_nacionales.LUCRO';

	/** the column name for the NUMERO_INSTITUCIONES_MIEMBRO field */
	const NUMERO_INSTITUCIONES_MIEMBRO = 'alpza_miembro_nacionales.NUMERO_INSTITUCIONES_MIEMBRO';

	/** the column name for the PORCENTAJE_COVERTURA_NACIONAL field */
	const PORCENTAJE_COVERTURA_NACIONAL = 'alpza_miembro_nacionales.PORCENTAJE_COVERTURA_NACIONAL';

	/** the column name for the LISTA_INSTITUCIONES_MIEMBRO field */
	const LISTA_INSTITUCIONES_MIEMBRO = 'alpza_miembro_nacionales.LISTA_INSTITUCIONES_MIEMBRO';

	/** the column name for the ESTATUTOS field */
	const ESTATUTOS = 'alpza_miembro_nacionales.ESTATUTOS';

	/** the column name for the ORGANIGRAMA field */
	const ORGANIGRAMA = 'alpza_miembro_nacionales.ORGANIGRAMA';

	/** the column name for the OTRA_ASOCIACION field */
	const OTRA_ASOCIACION = 'alpza_miembro_nacionales.OTRA_ASOCIACION';

	/** the column name for the DESCRIPCION field */
	const DESCRIPCION = 'alpza_miembro_nacionales.DESCRIPCION';

	/** the column name for the MISION field */
	const MISION = 'alpza_miembro_nacionales.MISION';

	/** the column name for the VISION field */
	const VISION = 'alpza_miembro_nacionales.VISION';

	/** the column name for the OBJETIVO field */
	const OBJETIVO = 'alpza_miembro_nacionales.OBJETIVO';

	/** the column name for the PANORAMA_GENERAL field */
	const PANORAMA_GENERAL = 'alpza_miembro_nacionales.PANORAMA_GENERAL';

	/** the column name for the PROYECTOS field */
	const PROYECTOS = 'alpza_miembro_nacionales.PROYECTOS';

	/** the column name for the AREA_TRABAJO field */
	const AREA_TRABAJO = 'alpza_miembro_nacionales.AREA_TRABAJO';

	/** the column name for the CONSIDERA_APOYO_ALPZA field */
	const CONSIDERA_APOYO_ALPZA = 'alpza_miembro_nacionales.CONSIDERA_APOYO_ALPZA';

	/**
	 * An identiy map to hold any loaded instances of AlpzaMiembroNacionales objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array AlpzaMiembroNacionales[]
	 */
	public static $instances = array();


	// symfony behavior

	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
	BasePeer::TYPE_PHPNAME => array ('IdAlpzaMiembroNacionales', 'AlpzaMiembroIdAlpzaMiembro', 'NombreFormal', 'Sigla', 'NumeroIdentificacion', 'AnoFundacion', 'AnoIngresoAlpza', 'DirectorNombre', 'DirectorEmail', 'PersonalPermanente', 'PersonalTemporal', 'DelegadoNombre', 'DelegadoApellido', 'DelegadoProfesion', 'DelegadoCargo', 'DelegadoEmail', 'Logo', 'Direccion', 'CodigoPostal', 'Pais', 'TelefonoCodCiudad', 'TelefonoCodPais', 'Telefono', 'Fax', 'Celular', 'Email', 'SitioWeb', 'NaturalezaJuridicaPublica', 'NaturalezaJuridicaPrivada', 'NaturalezaJuridicaMixta', 'Propietario', 'Lucro', 'NumeroInstitucionesMiembro', 'PorcentajeCoverturaNacional', 'ListaInstitucionesMiembro', 'Estatutos', 'Organigrama', 'OtraAsociacion', 'Descripcion', 'Mision', 'Vision', 'Objetivo', 'PanoramaGeneral', 'Proyectos', 'AreaTrabajo', 'ConsideraApoyoAlpza', ),
	BasePeer::TYPE_STUDLYPHPNAME => array ('idAlpzaMiembroNacionales', 'alpzaMiembroIdAlpzaMiembro', 'nombreFormal', 'sigla', 'numeroIdentificacion', 'anoFundacion', 'anoIngresoAlpza', 'directorNombre', 'directorEmail', 'personalPermanente', 'personalTemporal', 'delegadoNombre', 'delegadoApellido', 'delegadoProfesion', 'delegadoCargo', 'delegadoEmail', 'logo', 'direccion', 'codigoPostal', 'pais', 'telefonoCodCiudad', 'telefonoCodPais', 'telefono', 'fax', 'celular', 'email', 'sitioWeb', 'naturalezaJuridicaPublica', 'naturalezaJuridicaPrivada', 'naturalezaJuridicaMixta', 'propietario', 'lucro', 'numeroInstitucionesMiembro', 'porcentajeCoverturaNacional', 'listaInstitucionesMiembro', 'estatutos', 'organigrama', 'otraAsociacion', 'descripcion', 'mision', 'vision', 'objetivo', 'panoramaGeneral', 'proyectos', 'areaTrabajo', 'consideraApoyoAlpza', ),
	BasePeer::TYPE_COLNAME => array (self::ID_ALPZA_MIEMBRO_NACIONALES, self::ALPZA_MIEMBRO_ID_ALPZA_MIEMBRO, self::NOMBRE_FORMAL, self::SIGLA, self::NUMERO_IDENTIFICACION, self::ANO_FUNDACION, self::ANO_INGRESO_ALPZA, self::DIRECTOR_NOMBRE, self::DIRECTOR_EMAIL, self::PERSONAL_PERMANENTE, self::PERSONAL_TEMPORAL, self::DELEGADO_NOMBRE, self::DELEGADO_APELLIDO, self::DELEGADO_PROFESION, self::DELEGADO_CARGO, self::DELEGADO_EMAIL, self::LOGO, self::DIRECCION, self::CODIGO_POSTAL, self::PAIS, self::TELEFONO_COD_CIUDAD, self::TELEFONO_COD_PAIS, self::TELEFONO, self::FAX, self::CELULAR, self::EMAIL, self::SITIO_WEB, self::NATURALEZA_JURIDICA_PUBLICA, self::NATURALEZA_JURIDICA_PRIVADA, self::NATURALEZA_JURIDICA_MIXTA, self::PROPIETARIO, self::LUCRO, self::NUMERO_INSTITUCIONES_MIEMBRO, self::PORCENTAJE_COVERTURA_NACIONAL, self::LISTA_INSTITUCIONES_MIEMBRO, self::ESTATUTOS, self::ORGANIGRAMA, self::OTRA_ASOCIACION, self::DESCRIPCION, self::MISION, self::VISION, self::OBJETIVO, self::PANORAMA_GENERAL, self::PROYECTOS, self::AREA_TRABAJO, self::CONSIDERA_APOYO_ALPZA, ),
	BasePeer::TYPE_FIELDNAME => array ('id_alpza_miembro_nacionales', 'alpza_miembro_id_alpza_miembro', 'nombre_formal', 'sigla', 'numero_identificacion', 'ano_fundacion', 'ano_ingreso_alpza', 'director_nombre', 'director_email', 'personal_permanente', 'personal_temporal', 'delegado_nombre', 'delegado_apellido', 'delegado_profesion', 'delegado_cargo', 'delegado_email', 'logo', 'direccion', 'codigo_postal', 'pais', 'telefono_cod_ciudad', 'telefono_cod_pais', 'telefono', 'fax', 'celular', 'email', 'sitio_web', 'naturaleza_juridica_publica', 'naturaleza_juridica_privada', 'naturaleza_juridica_mixta', 'propietario', 'lucro', 'numero_instituciones_miembro', 'porcentaje_covertura_nacional', 'lista_instituciones_miembro', 'estatutos', 'organigrama', 'otra_asociacion', 'descripcion', 'mision', 'vision', 'objetivo', 'panorama_general', 'proyectos', 'area_trabajo', 'considera_apoyo_alpza', ),
	BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
	BasePeer::TYPE_PHPNAME => array ('IdAlpzaMiembroNacionales' => 0, 'AlpzaMiembroIdAlpzaMiembro' => 1, 'NombreFormal' => 2, 'Sigla' => 3, 'NumeroIdentificacion' => 4, 'AnoFundacion' => 5, 'AnoIngresoAlpza' => 6, 'DirectorNombre' => 7, 'DirectorEmail' => 8, 'PersonalPermanente' => 9, 'PersonalTemporal' => 10, 'DelegadoNombre' => 11, 'DelegadoApellido' => 12, 'DelegadoProfesion' => 13, 'DelegadoCargo' => 14, 'DelegadoEmail' => 15, 'Logo' => 16, 'Direccion' => 17, 'CodigoPostal' => 18, 'Pais' => 19, 'TelefonoCodCiudad' => 20, 'TelefonoCodPais' => 21, 'Telefono' => 22, 'Fax' => 23, 'Celular' => 24, 'Email' => 25, 'SitioWeb' => 26, 'NaturalezaJuridicaPublica' => 27, 'NaturalezaJuridicaPrivada' => 28, 'NaturalezaJuridicaMixta' => 29, 'Propietario' => 30, 'Lucro' => 31, 'NumeroInstitucionesMiembro' => 32, 'PorcentajeCoverturaNacional' => 33, 'ListaInstitucionesMiembro' => 34, 'Estatutos' => 35, 'Organigrama' => 36, 'OtraAsociacion' => 37, 'Descripcion' => 38, 'Mision' => 39, 'Vision' => 40, 'Objetivo' => 41, 'PanoramaGeneral' => 42, 'Proyectos' => 43, 'AreaTrabajo' => 44, 'ConsideraApoyoAlpza' => 45, ),
	BasePeer::TYPE_STUDLYPHPNAME => array ('idAlpzaMiembroNacionales' => 0, 'alpzaMiembroIdAlpzaMiembro' => 1, 'nombreFormal' => 2, 'sigla' => 3, 'numeroIdentificacion' => 4, 'anoFundacion' => 5, 'anoIngresoAlpza' => 6, 'directorNombre' => 7, 'directorEmail' => 8, 'personalPermanente' => 9, 'personalTemporal' => 10, 'delegadoNombre' => 11, 'delegadoApellido' => 12, 'delegadoProfesion' => 13, 'delegadoCargo' => 14, 'delegadoEmail' => 15, 'logo' => 16, 'direccion' => 17, 'codigoPostal' => 18, 'pais' => 19, 'telefonoCodCiudad' => 20, 'telefonoCodPais' => 21, 'telefono' => 22, 'fax' => 23, 'celular' => 24, 'email' => 25, 'sitioWeb' => 26, 'naturalezaJuridicaPublica' => 27, 'naturalezaJuridicaPrivada' => 28, 'naturalezaJuridicaMixta' => 29, 'propietario' => 30, 'lucro' => 31, 'numeroInstitucionesMiembro' => 32, 'porcentajeCoverturaNacional' => 33, 'listaInstitucionesMiembro' => 34, 'estatutos' => 35, 'organigrama' => 36, 'otraAsociacion' => 37, 'descripcion' => 38, 'mision' => 39, 'vision' => 40, 'objetivo' => 41, 'panoramaGeneral' => 42, 'proyectos' => 43, 'areaTrabajo' => 44, 'consideraApoyoAlpza' => 45, ),
	BasePeer::TYPE_COLNAME => array (self::ID_ALPZA_MIEMBRO_NACIONALES => 0, self::ALPZA_MIEMBRO_ID_ALPZA_MIEMBRO => 1, self::NOMBRE_FORMAL => 2, self::SIGLA => 3, self::NUMERO_IDENTIFICACION => 4, self::ANO_FUNDACION => 5, self::ANO_INGRESO_ALPZA => 6, self::DIRECTOR_NOMBRE => 7, self::DIRECTOR_EMAIL => 8, self::PERSONAL_PERMANENTE => 9, self::PERSONAL_TEMPORAL => 10, self::DELEGADO_NOMBRE => 11, self::DELEGADO_APELLIDO => 12, self::DELEGADO_PROFESION => 13, self::DELEGADO_CARGO => 14, self::DELEGADO_EMAIL => 15, self::LOGO => 16, self::DIRECCION => 17, self::CODIGO_POSTAL => 18, self::PAIS => 19, self::TELEFONO_COD_CIUDAD => 20, self::TELEFONO_COD_PAIS => 21, self::TELEFONO => 22, self::FAX => 23, self::CELULAR => 24, self::EMAIL => 25, self::SITIO_WEB => 26, self::NATURALEZA_JURIDICA_PUBLICA => 27, self::NATURALEZA_JURIDICA_PRIVADA => 28, self::NATURALEZA_JURIDICA_MIXTA => 29, self::PROPIETARIO => 30, self::LUCRO => 31, self::NUMERO_INSTITUCIONES_MIEMBRO => 32, self::PORCENTAJE_COVERTURA_NACIONAL => 33, self::LISTA_INSTITUCIONES_MIEMBRO => 34, self::ESTATUTOS => 35, self::ORGANIGRAMA => 36, self::OTRA_ASOCIACION => 37, self::DESCRIPCION => 38, self::MISION => 39, self::VISION => 40, self::OBJETIVO => 41, self::PANORAMA_GENERAL => 42, self::PROYECTOS => 43, self::AREA_TRABAJO => 44, self::CONSIDERA_APOYO_ALPZA => 45, ),
	BasePeer::TYPE_FIELDNAME => array ('id_alpza_miembro_nacionales' => 0, 'alpza_miembro_id_alpza_miembro' => 1, 'nombre_formal' => 2, 'sigla' => 3, 'numero_identificacion' => 4, 'ano_fundacion' => 5, 'ano_ingreso_alpza' => 6, 'director_nombre' => 7, 'director_email' => 8, 'personal_permanente' => 9, 'personal_temporal' => 10, 'delegado_nombre' => 11, 'delegado_apellido' => 12, 'delegado_profesion' => 13, 'delegado_cargo' => 14, 'delegado_email' => 15, 'logo' => 16, 'direccion' => 17, 'codigo_postal' => 18, 'pais' => 19, 'telefono_cod_ciudad' => 20, 'telefono_cod_pais' => 21, 'telefono' => 22, 'fax' => 23, 'celular' => 24, 'email' => 25, 'sitio_web' => 26, 'naturaleza_juridica_publica' => 27, 'naturaleza_juridica_privada' => 28, 'naturaleza_juridica_mixta' => 29, 'propietario' => 30, 'lucro' => 31, 'numero_instituciones_miembro' => 32, 'porcentaje_covertura_nacional' => 33, 'lista_instituciones_miembro' => 34, 'estatutos' => 35, 'organigrama' => 36, 'otra_asociacion' => 37, 'descripcion' => 38, 'mision' => 39, 'vision' => 40, 'objetivo' => 41, 'panorama_general' => 42, 'proyectos' => 43, 'area_trabajo' => 44, 'considera_apoyo_alpza' => 45, ),
	BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. AlpzaMiembroNacionalesPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(AlpzaMiembroNacionalesPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::ID_ALPZA_MIEMBRO_NACIONALES);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::ALPZA_MIEMBRO_ID_ALPZA_MIEMBRO);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::NOMBRE_FORMAL);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::SIGLA);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::NUMERO_IDENTIFICACION);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::ANO_FUNDACION);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::ANO_INGRESO_ALPZA);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::DIRECTOR_NOMBRE);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::DIRECTOR_EMAIL);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::PERSONAL_PERMANENTE);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::PERSONAL_TEMPORAL);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::DELEGADO_NOMBRE);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::DELEGADO_APELLIDO);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::DELEGADO_PROFESION);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::DELEGADO_CARGO);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::DELEGADO_EMAIL);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::LOGO);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::DIRECCION);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::CODIGO_POSTAL);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::PAIS);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::TELEFONO_COD_CIUDAD);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::TELEFONO_COD_PAIS);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::TELEFONO);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::FAX);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::CELULAR);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::EMAIL);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::SITIO_WEB);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::NATURALEZA_JURIDICA_PUBLICA);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::NATURALEZA_JURIDICA_PRIVADA);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::NATURALEZA_JURIDICA_MIXTA);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::PROPIETARIO);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::LUCRO);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::NUMERO_INSTITUCIONES_MIEMBRO);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::PORCENTAJE_COVERTURA_NACIONAL);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::LISTA_INSTITUCIONES_MIEMBRO);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::ESTATUTOS);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::ORGANIGRAMA);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::OTRA_ASOCIACION);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::DESCRIPCION);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::MISION);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::VISION);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::OBJETIVO);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::PANORAMA_GENERAL);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::PROYECTOS);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::AREA_TRABAJO);
		$criteria->addSelectColumn(AlpzaMiembroNacionalesPeer::CONSIDERA_APOYO_ALPZA);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AlpzaMiembroNacionalesPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AlpzaMiembroNacionalesPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroNacionalesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
			call_user_func($sf_hook, 'BaseAlpzaMiembroNacionalesPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     AlpzaMiembroNacionales
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = AlpzaMiembroNacionalesPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return AlpzaMiembroNacionalesPeer::populateObjects(AlpzaMiembroNacionalesPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroNacionalesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			AlpzaMiembroNacionalesPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
			call_user_func($sf_hook, 'BaseAlpzaMiembroNacionalesPeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      AlpzaMiembroNacionales $value A AlpzaMiembroNacionales object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(AlpzaMiembroNacionales $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getIdAlpzaMiembroNacionales();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A AlpzaMiembroNacionales object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof AlpzaMiembroNacionales) {
				$key = (string) $value->getIdAlpzaMiembroNacionales();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or AlpzaMiembroNacionales object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     AlpzaMiembroNacionales Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}

	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}

	/**
	 * Method to invalidate the instance pool of all tables related to alpza_miembro_nacionales
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();

		// set the class once to avoid overhead in the loop
		$cls = AlpzaMiembroNacionalesPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = AlpzaMiembroNacionalesPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = AlpzaMiembroNacionalesPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				AlpzaMiembroNacionalesPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related AlpzaMiembro table
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAlpzaMiembro(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AlpzaMiembroNacionalesPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AlpzaMiembroNacionalesPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroNacionalesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(AlpzaMiembroNacionalesPeer::ALPZA_MIEMBRO_ID_ALPZA_MIEMBRO, AlpzaMiembroPeer::ID_ALPZA_MIEMBRO, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
			call_user_func($sf_hook, 'BaseAlpzaMiembroNacionalesPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of AlpzaMiembroNacionales objects pre-filled with their AlpzaMiembro objects.
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of AlpzaMiembroNacionales objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAlpzaMiembro(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AlpzaMiembroNacionalesPeer::addSelectColumns($criteria);
		$startcol = (AlpzaMiembroNacionalesPeer::NUM_COLUMNS - AlpzaMiembroNacionalesPeer::NUM_LAZY_LOAD_COLUMNS);
		AlpzaMiembroPeer::addSelectColumns($criteria);

		$criteria->addJoin(AlpzaMiembroNacionalesPeer::ALPZA_MIEMBRO_ID_ALPZA_MIEMBRO, AlpzaMiembroPeer::ID_ALPZA_MIEMBRO, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
			call_user_func($sf_hook, 'BaseAlpzaMiembroNacionalesPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AlpzaMiembroNacionalesPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AlpzaMiembroNacionalesPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$cls = AlpzaMiembroNacionalesPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AlpzaMiembroNacionalesPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = AlpzaMiembroPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = AlpzaMiembroPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = AlpzaMiembroPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					AlpzaMiembroPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (AlpzaMiembroNacionales) to $obj2 (AlpzaMiembro)
				$obj2->addAlpzaMiembroNacionales($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AlpzaMiembroNacionalesPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AlpzaMiembroNacionalesPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroNacionalesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(AlpzaMiembroNacionalesPeer::ALPZA_MIEMBRO_ID_ALPZA_MIEMBRO, AlpzaMiembroPeer::ID_ALPZA_MIEMBRO, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
			call_user_func($sf_hook, 'BaseAlpzaMiembroNacionalesPeer', $criteria, $con);
		}

		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of AlpzaMiembroNacionales objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $criteria
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of AlpzaMiembroNacionales objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $criteria, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$criteria = clone $criteria;

		// Set the correct dbName if it has not been overridden
		if ($criteria->getDbName() == Propel::getDefaultDB()) {
			$criteria->setDbName(self::DATABASE_NAME);
		}

		AlpzaMiembroNacionalesPeer::addSelectColumns($criteria);
		$startcol2 = (AlpzaMiembroNacionalesPeer::NUM_COLUMNS - AlpzaMiembroNacionalesPeer::NUM_LAZY_LOAD_COLUMNS);

		AlpzaMiembroPeer::addSelectColumns($criteria);
		$startcol3 = $startcol2 + (AlpzaMiembroPeer::NUM_COLUMNS - AlpzaMiembroPeer::NUM_LAZY_LOAD_COLUMNS);

		$criteria->addJoin(AlpzaMiembroNacionalesPeer::ALPZA_MIEMBRO_ID_ALPZA_MIEMBRO, AlpzaMiembroPeer::ID_ALPZA_MIEMBRO, $join_behavior);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
			call_user_func($sf_hook, 'BaseAlpzaMiembroNacionalesPeer', $criteria, $con);
		}

		$stmt = BasePeer::doSelect($criteria, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AlpzaMiembroNacionalesPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AlpzaMiembroNacionalesPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$cls = AlpzaMiembroNacionalesPeer::getOMClass(false);

				$obj1 = new $cls();
				$obj1->hydrate($row);
				AlpzaMiembroNacionalesPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined AlpzaMiembro rows

			$key2 = AlpzaMiembroPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = AlpzaMiembroPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$cls = AlpzaMiembroPeer::getOMClass(false);

					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					AlpzaMiembroPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (AlpzaMiembroNacionales) to the collection in $obj2 (AlpzaMiembro)
				$obj2->addAlpzaMiembroNacionales($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
		$dbMap = Propel::getDatabaseMap(BaseAlpzaMiembroNacionalesPeer::DATABASE_NAME);
		if (!$dbMap->hasTable(BaseAlpzaMiembroNacionalesPeer::TABLE_NAME))
		{
			$dbMap->addTableObject(new AlpzaMiembroNacionalesTableMap());
		}
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? AlpzaMiembroNacionalesPeer::CLASS_DEFAULT : AlpzaMiembroNacionalesPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a AlpzaMiembroNacionales or Criteria object.
	 *
	 * @param      mixed $values Criteria or AlpzaMiembroNacionales object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables('BaseAlpzaMiembroNacionalesPeer:doInsert:pre') as $sf_hook)
		{
			if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseAlpzaMiembroNacionalesPeer', $values, $con))
			{
				return $sf_hook_retval;
			}
		}

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroNacionalesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from AlpzaMiembroNacionales object
		}

		if ($criteria->containsKey(AlpzaMiembroNacionalesPeer::ID_ALPZA_MIEMBRO_NACIONALES) && $criteria->keyContainsValue(AlpzaMiembroNacionalesPeer::ID_ALPZA_MIEMBRO_NACIONALES) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.AlpzaMiembroNacionalesPeer::ID_ALPZA_MIEMBRO_NACIONALES.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables('BaseAlpzaMiembroNacionalesPeer:doInsert:post') as $sf_hook)
		{
			call_user_func($sf_hook, 'BaseAlpzaMiembroNacionalesPeer', $values, $con, $pk);
		}

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a AlpzaMiembroNacionales or Criteria object.
	 *
	 * @param      mixed $values Criteria or AlpzaMiembroNacionales object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables('BaseAlpzaMiembroNacionalesPeer:doUpdate:pre') as $sf_hook)
		{
			if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BaseAlpzaMiembroNacionalesPeer', $values, $con))
			{
				return $sf_hook_retval;
			}
		}

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroNacionalesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(AlpzaMiembroNacionalesPeer::ID_ALPZA_MIEMBRO_NACIONALES);
			$selectCriteria->add(AlpzaMiembroNacionalesPeer::ID_ALPZA_MIEMBRO_NACIONALES, $criteria->remove(AlpzaMiembroNacionalesPeer::ID_ALPZA_MIEMBRO_NACIONALES), $comparison);

		} else { // $values is AlpzaMiembroNacionales object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

		// symfony_behaviors behavior
		foreach (sfMixer::getCallables('BaseAlpzaMiembroNacionalesPeer:doUpdate:post') as $sf_hook)
		{
			call_user_func($sf_hook, 'BaseAlpzaMiembroNacionalesPeer', $values, $con, $ret);
		}

		return $ret;
	}

	/**
	 * Method to DELETE all rows from the alpza_miembro_nacionales table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroNacionalesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(AlpzaMiembroNacionalesPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			AlpzaMiembroNacionalesPeer::clearInstancePool();
			AlpzaMiembroNacionalesPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a AlpzaMiembroNacionales or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or AlpzaMiembroNacionales object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doDelete($values, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroNacionalesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			AlpzaMiembroNacionalesPeer::clearInstancePool();
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof AlpzaMiembroNacionales) { // it's a model object
			// invalidate the cache for this single object
			AlpzaMiembroNacionalesPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(AlpzaMiembroNacionalesPeer::ID_ALPZA_MIEMBRO_NACIONALES, (array) $values, Criteria::IN);
			// invalidate the cache for this object(s)
			foreach ((array) $values as $singleval) {
				AlpzaMiembroNacionalesPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
				
			$affectedRows += BasePeer::doDelete($criteria, $con);
			AlpzaMiembroNacionalesPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given AlpzaMiembroNacionales object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      AlpzaMiembroNacionales $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(AlpzaMiembroNacionales $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(AlpzaMiembroNacionalesPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(AlpzaMiembroNacionalesPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(AlpzaMiembroNacionalesPeer::DATABASE_NAME, AlpzaMiembroNacionalesPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     AlpzaMiembroNacionales
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = AlpzaMiembroNacionalesPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroNacionalesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(AlpzaMiembroNacionalesPeer::DATABASE_NAME);
		$criteria->add(AlpzaMiembroNacionalesPeer::ID_ALPZA_MIEMBRO_NACIONALES, $pk);

		$v = AlpzaMiembroNacionalesPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroNacionalesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(AlpzaMiembroNacionalesPeer::DATABASE_NAME);
			$criteria->add(AlpzaMiembroNacionalesPeer::ID_ALPZA_MIEMBRO_NACIONALES, $pks, Criteria::IN);
			$objs = AlpzaMiembroNacionalesPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior

	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
		return array();
	}

	// symfony_behaviors behavior

	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
		if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
		{
			return sprintf('BaseAlpzaMiembroNacionalesPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
		}

		throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BaseAlpzaMiembroNacionalesPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BaseAlpzaMiembroNacionalesPeer::buildTableMap();

