<?php

/**
 * Base class that represents a row from the 'alpza_miembro_finanzas' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Nov 24 15:15:36 2012
 *
 * @package    lib.model.om
 */
abstract class BaseAlpzaMiembroFinanzas extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AlpzaMiembroFinanzasPeer
	 */
	protected static $peer;

	/**
	 * The value for the id_alpza_miembro_finanzas field.
	 * @var        int
	 */
	protected $id_alpza_miembro_finanzas;

	/**
	 * The value for the id_alpza_miembro field.
	 * @var        int
	 */
	protected $id_alpza_miembro;

	/**
	 * The value for the cuenta field.
	 * @var        string
	 */
	protected $cuenta;

	/**
	 * The value for the institucion field.
	 * @var        string
	 */
	protected $institucion;

	/**
	 * The value for the direccion field.
	 * @var        string
	 */
	protected $direccion;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the duracion field.
	 * @var        string
	 */
	protected $duracion;

	/**
	 * The value for the fecha_ingreso field.
	 * @var        string
	 */
	protected $fecha_ingreso;

	/**
	 * The value for the fecha_edicion field.
	 * @var        string
	 */
	protected $fecha_edicion;

	/**
	 * The value for the fecha_publicacion field.
	 * @var        string
	 */
	protected $fecha_publicacion;

	/**
	 * @var        AlpzaMiembro
	 */
	protected $aAlpzaMiembro;

	/**
	 * @var        array AlpzaMiembroEstadoFinancieroHistorial[] Collection to store aggregation of AlpzaMiembroEstadoFinancieroHistorial objects.
	 */
	protected $collAlpzaMiembroEstadoFinancieroHistorials;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAlpzaMiembroEstadoFinancieroHistorials.
	 */
	private $lastAlpzaMiembroEstadoFinancieroHistorialCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior

	const PEER = 'AlpzaMiembroFinanzasPeer';

	/**
	 * Get the [id_alpza_miembro_finanzas] column value.
	 *
	 * @return     int
	 */
	public function getIdAlpzaMiembroFinanzas()
	{
		return $this->id_alpza_miembro_finanzas;
	}

	/**
	 * Get the [id_alpza_miembro] column value.
	 *
	 * @return     int
	 */
	public function getIdAlpzaMiembro()
	{
		return $this->id_alpza_miembro;
	}

	/**
	 * Get the [cuenta] column value.
	 *
	 * @return     string
	 */
	public function getCuenta()
	{
		return $this->cuenta;
	}

	/**
	 * Get the [institucion] column value.
	 *
	 * @return     string
	 */
	public function getInstitucion()
	{
		return $this->institucion;
	}

	/**
	 * Get the [direccion] column value.
	 *
	 * @return     string
	 */
	public function getDireccion()
	{
		return $this->direccion;
	}

	/**
	 * Get the [email] column value.
	 *
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [duracion] column value.
	 *
	 * @return     string
	 */
	public function getDuracion()
	{
		return $this->duracion;
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_ingreso] column value.
	 *
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaIngreso($format = 'Y-m-d')
	{
		if ($this->fecha_ingreso === null) {
			return null;
		}


		if ($this->fecha_ingreso === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_ingreso);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_ingreso, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_edicion] column value.
	 *
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaEdicion($format = 'Y-m-d')
	{
		if ($this->fecha_edicion === null) {
			return null;
		}


		if ($this->fecha_edicion === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_edicion);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_edicion, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [fecha_publicacion] column value.
	 *
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getFechaPublicacion($format = 'Y-m-d')
	{
		if ($this->fecha_publicacion === null) {
			return null;
		}


		if ($this->fecha_publicacion === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->fecha_publicacion);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->fecha_publicacion, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id_alpza_miembro_finanzas] column.
	 *
	 * @param      int $v new value
	 * @return     AlpzaMiembroFinanzas The current object (for fluent API support)
	 */
	public function setIdAlpzaMiembroFinanzas($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_alpza_miembro_finanzas !== $v) {
			$this->id_alpza_miembro_finanzas = $v;
			$this->modifiedColumns[] = AlpzaMiembroFinanzasPeer::ID_ALPZA_MIEMBRO_FINANZAS;
		}

		return $this;
	} // setIdAlpzaMiembroFinanzas()

	/**
	 * Set the value of [id_alpza_miembro] column.
	 *
	 * @param      int $v new value
	 * @return     AlpzaMiembroFinanzas The current object (for fluent API support)
	 */
	public function setIdAlpzaMiembro($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id_alpza_miembro !== $v) {
			$this->id_alpza_miembro = $v;
			$this->modifiedColumns[] = AlpzaMiembroFinanzasPeer::ID_ALPZA_MIEMBRO;
		}

		if ($this->aAlpzaMiembro !== null && $this->aAlpzaMiembro->getIdAlpzaMiembro() !== $v) {
			$this->aAlpzaMiembro = null;
		}

		return $this;
	} // setIdAlpzaMiembro()

	/**
	 * Set the value of [cuenta] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroFinanzas The current object (for fluent API support)
	 */
	public function setCuenta($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cuenta !== $v) {
			$this->cuenta = $v;
			$this->modifiedColumns[] = AlpzaMiembroFinanzasPeer::CUENTA;
		}

		return $this;
	} // setCuenta()

	/**
	 * Set the value of [institucion] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroFinanzas The current object (for fluent API support)
	 */
	public function setInstitucion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->institucion !== $v) {
			$this->institucion = $v;
			$this->modifiedColumns[] = AlpzaMiembroFinanzasPeer::INSTITUCION;
		}

		return $this;
	} // setInstitucion()

	/**
	 * Set the value of [direccion] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroFinanzas The current object (for fluent API support)
	 */
	public function setDireccion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->direccion !== $v) {
			$this->direccion = $v;
			$this->modifiedColumns[] = AlpzaMiembroFinanzasPeer::DIRECCION;
		}

		return $this;
	} // setDireccion()

	/**
	 * Set the value of [email] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroFinanzas The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = AlpzaMiembroFinanzasPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [duracion] column.
	 *
	 * @param      string $v new value
	 * @return     AlpzaMiembroFinanzas The current object (for fluent API support)
	 */
	public function setDuracion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->duracion !== $v) {
			$this->duracion = $v;
			$this->modifiedColumns[] = AlpzaMiembroFinanzasPeer::DURACION;
		}

		return $this;
	} // setDuracion()

	/**
	 * Sets the value of [fecha_ingreso] column to a normalized version of the date/time value specified.
	 *
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AlpzaMiembroFinanzas The current object (for fluent API support)
	 */
	public function setFechaIngreso($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_ingreso !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_ingreso !== null && $tmpDt = new DateTime($this->fecha_ingreso)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match
			)
			{
				$this->fecha_ingreso = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = AlpzaMiembroFinanzasPeer::FECHA_INGRESO;
			}
		} // if either are not null

		return $this;
	} // setFechaIngreso()

	/**
	 * Sets the value of [fecha_edicion] column to a normalized version of the date/time value specified.
	 *
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AlpzaMiembroFinanzas The current object (for fluent API support)
	 */
	public function setFechaEdicion($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_edicion !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_edicion !== null && $tmpDt = new DateTime($this->fecha_edicion)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match
			)
			{
				$this->fecha_edicion = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = AlpzaMiembroFinanzasPeer::FECHA_EDICION;
			}
		} // if either are not null

		return $this;
	} // setFechaEdicion()

	/**
	 * Sets the value of [fecha_publicacion] column to a normalized version of the date/time value specified.
	 *
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AlpzaMiembroFinanzas The current object (for fluent API support)
	 */
	public function setFechaPublicacion($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->fecha_publicacion !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->fecha_publicacion !== null && $tmpDt = new DateTime($this->fecha_publicacion)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match
			)
			{
				$this->fecha_publicacion = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = AlpzaMiembroFinanzasPeer::FECHA_PUBLICACION;
			}
		} // if either are not null

		return $this;
	} // setFechaPublicacion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id_alpza_miembro_finanzas = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->id_alpza_miembro = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->cuenta = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->institucion = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->direccion = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->email = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->duracion = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->fecha_ingreso = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->fecha_edicion = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->fecha_publicacion = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = AlpzaMiembroFinanzasPeer::NUM_COLUMNS - AlpzaMiembroFinanzasPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating AlpzaMiembroFinanzas object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aAlpzaMiembro !== null && $this->id_alpza_miembro !== $this->aAlpzaMiembro->getIdAlpzaMiembro()) {
			$this->aAlpzaMiembro = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroFinanzasPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AlpzaMiembroFinanzasPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aAlpzaMiembro = null;
			$this->collAlpzaMiembroEstadoFinancieroHistorials = null;
			$this->lastAlpzaMiembroEstadoFinancieroHistorialCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroFinanzasPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAlpzaMiembroFinanzas:delete:pre') as $callable)
			{
				if (call_user_func($callable, $this, $con))
				{
					$con->commit();
						
					return;
				}
			}

			if ($ret) {
				AlpzaMiembroFinanzasPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAlpzaMiembroFinanzas:delete:post') as $callable)
				{
					call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AlpzaMiembroFinanzasPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAlpzaMiembroFinanzas:save:pre') as $callable)
			{
				if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
				{
					$con->commit();
						
					return $affectedRows;
				}
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAlpzaMiembroFinanzas:save:post') as $callable)
				{
					call_user_func($callable, $this, $con, $affectedRows);
				}

				AlpzaMiembroFinanzasPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAlpzaMiembro !== null) {
				if ($this->aAlpzaMiembro->isModified() || $this->aAlpzaMiembro->isNew()) {
					$affectedRows += $this->aAlpzaMiembro->save($con);
				}
				$this->setAlpzaMiembro($this->aAlpzaMiembro);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AlpzaMiembroFinanzasPeer::ID_ALPZA_MIEMBRO_FINANZAS;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AlpzaMiembroFinanzasPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
					// should always be true here (even though technically
					// BasePeer::doInsert() can insert multiple rows).

					$this->setIdAlpzaMiembroFinanzas($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AlpzaMiembroFinanzasPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAlpzaMiembroEstadoFinancieroHistorials !== null) {
				foreach ($this->collAlpzaMiembroEstadoFinancieroHistorials as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAlpzaMiembro !== null) {
				if (!$this->aAlpzaMiembro->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAlpzaMiembro->getValidationFailures());
				}
			}


			if (($retval = AlpzaMiembroFinanzasPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


			if ($this->collAlpzaMiembroEstadoFinancieroHistorials !== null) {
				foreach ($this->collAlpzaMiembroEstadoFinancieroHistorials as $referrerFK) {
					if (!$referrerFK->validate($columns)) {
						$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
					}
				}
			}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AlpzaMiembroFinanzasPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getIdAlpzaMiembroFinanzas();
				break;
			case 1:
				return $this->getIdAlpzaMiembro();
				break;
			case 2:
				return $this->getCuenta();
				break;
			case 3:
				return $this->getInstitucion();
				break;
			case 4:
				return $this->getDireccion();
				break;
			case 5:
				return $this->getEmail();
				break;
			case 6:
				return $this->getDuracion();
				break;
			case 7:
				return $this->getFechaIngreso();
				break;
			case 8:
				return $this->getFechaEdicion();
				break;
			case 9:
				return $this->getFechaPublicacion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AlpzaMiembroFinanzasPeer::getFieldNames($keyType);
		$result = array(
		$keys[0] => $this->getIdAlpzaMiembroFinanzas(),
		$keys[1] => $this->getIdAlpzaMiembro(),
		$keys[2] => $this->getCuenta(),
		$keys[3] => $this->getInstitucion(),
		$keys[4] => $this->getDireccion(),
		$keys[5] => $this->getEmail(),
		$keys[6] => $this->getDuracion(),
		$keys[7] => $this->getFechaIngreso(),
		$keys[8] => $this->getFechaEdicion(),
		$keys[9] => $this->getFechaPublicacion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AlpzaMiembroFinanzasPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setIdAlpzaMiembroFinanzas($value);
				break;
			case 1:
				$this->setIdAlpzaMiembro($value);
				break;
			case 2:
				$this->setCuenta($value);
				break;
			case 3:
				$this->setInstitucion($value);
				break;
			case 4:
				$this->setDireccion($value);
				break;
			case 5:
				$this->setEmail($value);
				break;
			case 6:
				$this->setDuracion($value);
				break;
			case 7:
				$this->setFechaIngreso($value);
				break;
			case 8:
				$this->setFechaEdicion($value);
				break;
			case 9:
				$this->setFechaPublicacion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AlpzaMiembroFinanzasPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setIdAlpzaMiembroFinanzas($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setIdAlpzaMiembro($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setCuenta($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setInstitucion($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDireccion($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setEmail($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDuracion($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setFechaIngreso($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFechaEdicion($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setFechaPublicacion($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AlpzaMiembroFinanzasPeer::DATABASE_NAME);

		if ($this->isColumnModified(AlpzaMiembroFinanzasPeer::ID_ALPZA_MIEMBRO_FINANZAS)) $criteria->add(AlpzaMiembroFinanzasPeer::ID_ALPZA_MIEMBRO_FINANZAS, $this->id_alpza_miembro_finanzas);
		if ($this->isColumnModified(AlpzaMiembroFinanzasPeer::ID_ALPZA_MIEMBRO)) $criteria->add(AlpzaMiembroFinanzasPeer::ID_ALPZA_MIEMBRO, $this->id_alpza_miembro);
		if ($this->isColumnModified(AlpzaMiembroFinanzasPeer::CUENTA)) $criteria->add(AlpzaMiembroFinanzasPeer::CUENTA, $this->cuenta);
		if ($this->isColumnModified(AlpzaMiembroFinanzasPeer::INSTITUCION)) $criteria->add(AlpzaMiembroFinanzasPeer::INSTITUCION, $this->institucion);
		if ($this->isColumnModified(AlpzaMiembroFinanzasPeer::DIRECCION)) $criteria->add(AlpzaMiembroFinanzasPeer::DIRECCION, $this->direccion);
		if ($this->isColumnModified(AlpzaMiembroFinanzasPeer::EMAIL)) $criteria->add(AlpzaMiembroFinanzasPeer::EMAIL, $this->email);
		if ($this->isColumnModified(AlpzaMiembroFinanzasPeer::DURACION)) $criteria->add(AlpzaMiembroFinanzasPeer::DURACION, $this->duracion);
		if ($this->isColumnModified(AlpzaMiembroFinanzasPeer::FECHA_INGRESO)) $criteria->add(AlpzaMiembroFinanzasPeer::FECHA_INGRESO, $this->fecha_ingreso);
		if ($this->isColumnModified(AlpzaMiembroFinanzasPeer::FECHA_EDICION)) $criteria->add(AlpzaMiembroFinanzasPeer::FECHA_EDICION, $this->fecha_edicion);
		if ($this->isColumnModified(AlpzaMiembroFinanzasPeer::FECHA_PUBLICACION)) $criteria->add(AlpzaMiembroFinanzasPeer::FECHA_PUBLICACION, $this->fecha_publicacion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AlpzaMiembroFinanzasPeer::DATABASE_NAME);

		$criteria->add(AlpzaMiembroFinanzasPeer::ID_ALPZA_MIEMBRO_FINANZAS, $this->id_alpza_miembro_finanzas);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getIdAlpzaMiembroFinanzas();
	}

	/**
	 * Generic method to set the primary key (id_alpza_miembro_finanzas column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setIdAlpzaMiembroFinanzas($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of AlpzaMiembroFinanzas (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setIdAlpzaMiembro($this->id_alpza_miembro);

		$copyObj->setCuenta($this->cuenta);

		$copyObj->setInstitucion($this->institucion);

		$copyObj->setDireccion($this->direccion);

		$copyObj->setEmail($this->email);

		$copyObj->setDuracion($this->duracion);

		$copyObj->setFechaIngreso($this->fecha_ingreso);

		$copyObj->setFechaEdicion($this->fecha_edicion);

		$copyObj->setFechaPublicacion($this->fecha_publicacion);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAlpzaMiembroEstadoFinancieroHistorials() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAlpzaMiembroEstadoFinancieroHistorial($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setIdAlpzaMiembroFinanzas(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     AlpzaMiembroFinanzas Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AlpzaMiembroFinanzasPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AlpzaMiembroFinanzasPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a AlpzaMiembro object.
	 *
	 * @param      AlpzaMiembro $v
	 * @return     AlpzaMiembroFinanzas The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAlpzaMiembro(AlpzaMiembro $v = null)
	{
		if ($v === null) {
			$this->setIdAlpzaMiembro(NULL);
		} else {
			$this->setIdAlpzaMiembro($v->getIdAlpzaMiembro());
		}

		$this->aAlpzaMiembro = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the AlpzaMiembro object, it will not be re-added.
		if ($v !== null) {
			$v->addAlpzaMiembroFinanzas($this);
		}

		return $this;
	}


	/**
	 * Get the associated AlpzaMiembro object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     AlpzaMiembro The associated AlpzaMiembro object.
	 * @throws     PropelException
	 */
	public function getAlpzaMiembro(PropelPDO $con = null)
	{
		if ($this->aAlpzaMiembro === null && ($this->id_alpza_miembro !== null)) {
			$this->aAlpzaMiembro = AlpzaMiembroPeer::retrieveByPk($this->id_alpza_miembro);
			/* The following can be used additionally to
			 guarantee the related object contains a reference
			 to this object.  This level of coupling may, however, be
			 undesirable since it could result in an only partially populated collection
			 in the referenced object.
			 $this->aAlpzaMiembro->addAlpzaMiembroFinanzass($this);
			 */
		}
		return $this->aAlpzaMiembro;
	}

	/**
	 * Clears out the collAlpzaMiembroEstadoFinancieroHistorials collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAlpzaMiembroEstadoFinancieroHistorials()
	 */
	public function clearAlpzaMiembroEstadoFinancieroHistorials()
	{
		$this->collAlpzaMiembroEstadoFinancieroHistorials = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAlpzaMiembroEstadoFinancieroHistorials collection (array).
	 *
	 * By default this just sets the collAlpzaMiembroEstadoFinancieroHistorials collection to an empty array (like clearcollAlpzaMiembroEstadoFinancieroHistorials());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAlpzaMiembroEstadoFinancieroHistorials()
	{
		$this->collAlpzaMiembroEstadoFinancieroHistorials = array();
	}

	/**
	 * Gets an array of AlpzaMiembroEstadoFinancieroHistorial objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this AlpzaMiembroFinanzas has previously been saved, it will retrieve
	 * related AlpzaMiembroEstadoFinancieroHistorials from storage. If this AlpzaMiembroFinanzas is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AlpzaMiembroEstadoFinancieroHistorial[]
	 * @throws     PropelException
	 */
	public function getAlpzaMiembroEstadoFinancieroHistorials($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AlpzaMiembroFinanzasPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAlpzaMiembroEstadoFinancieroHistorials === null) {
			if ($this->isNew()) {
				$this->collAlpzaMiembroEstadoFinancieroHistorials = array();
			} else {

				$criteria->add(AlpzaMiembroEstadoFinancieroHistorialPeer::ID_ALPZA_MIEMBRO_FINANZAS, $this->id_alpza_miembro_finanzas);

				AlpzaMiembroEstadoFinancieroHistorialPeer::addSelectColumns($criteria);
				$this->collAlpzaMiembroEstadoFinancieroHistorials = AlpzaMiembroEstadoFinancieroHistorialPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AlpzaMiembroEstadoFinancieroHistorialPeer::ID_ALPZA_MIEMBRO_FINANZAS, $this->id_alpza_miembro_finanzas);

				AlpzaMiembroEstadoFinancieroHistorialPeer::addSelectColumns($criteria);
				if (!isset($this->lastAlpzaMiembroEstadoFinancieroHistorialCriteria) || !$this->lastAlpzaMiembroEstadoFinancieroHistorialCriteria->equals($criteria)) {
					$this->collAlpzaMiembroEstadoFinancieroHistorials = AlpzaMiembroEstadoFinancieroHistorialPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAlpzaMiembroEstadoFinancieroHistorialCriteria = $criteria;
		return $this->collAlpzaMiembroEstadoFinancieroHistorials;
	}

	/**
	 * Returns the number of related AlpzaMiembroEstadoFinancieroHistorial objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AlpzaMiembroEstadoFinancieroHistorial objects.
	 * @throws     PropelException
	 */
	public function countAlpzaMiembroEstadoFinancieroHistorials(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AlpzaMiembroFinanzasPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAlpzaMiembroEstadoFinancieroHistorials === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AlpzaMiembroEstadoFinancieroHistorialPeer::ID_ALPZA_MIEMBRO_FINANZAS, $this->id_alpza_miembro_finanzas);

				$count = AlpzaMiembroEstadoFinancieroHistorialPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AlpzaMiembroEstadoFinancieroHistorialPeer::ID_ALPZA_MIEMBRO_FINANZAS, $this->id_alpza_miembro_finanzas);

				if (!isset($this->lastAlpzaMiembroEstadoFinancieroHistorialCriteria) || !$this->lastAlpzaMiembroEstadoFinancieroHistorialCriteria->equals($criteria)) {
					$count = AlpzaMiembroEstadoFinancieroHistorialPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAlpzaMiembroEstadoFinancieroHistorials);
				}
			} else {
				$count = count($this->collAlpzaMiembroEstadoFinancieroHistorials);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AlpzaMiembroEstadoFinancieroHistorial object to this object
	 * through the AlpzaMiembroEstadoFinancieroHistorial foreign key attribute.
	 *
	 * @param      AlpzaMiembroEstadoFinancieroHistorial $l AlpzaMiembroEstadoFinancieroHistorial
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAlpzaMiembroEstadoFinancieroHistorial(AlpzaMiembroEstadoFinancieroHistorial $l)
	{
		if ($this->collAlpzaMiembroEstadoFinancieroHistorials === null) {
			$this->initAlpzaMiembroEstadoFinancieroHistorials();
		}
		if (!in_array($l, $this->collAlpzaMiembroEstadoFinancieroHistorials, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAlpzaMiembroEstadoFinancieroHistorials, $l);
			$l->setAlpzaMiembroFinanzas($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAlpzaMiembroEstadoFinancieroHistorials) {
				foreach ((array) $this->collAlpzaMiembroEstadoFinancieroHistorials as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAlpzaMiembroEstadoFinancieroHistorials = null;
		$this->aAlpzaMiembro = null;
	}

	// symfony_behaviors behavior

	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
		if (!$callable = sfMixer::getCallable('BaseAlpzaMiembroFinanzas:'.$method))
		{
			throw new sfException(sprintf('Call to undefined method BaseAlpzaMiembroFinanzas::%s', $method));
		}

		array_unshift($arguments, $this);

		return call_user_func_array($callable, $arguments);
	}

} // BaseAlpzaMiembroFinanzas
