<?php

/**
 * AlpzaMiembroAsociados form base class.
 *
 * @method AlpzaMiembroAsociados getObject() Returns the current form's model object
 *
 * @package    alpzaDev
 * @subpackage form
 * @author     Your name here
 */
abstract class BaseAlpzaMiembroAsociadosForm extends BaseFormPropel
{
	public function setup()
	{
		$this->setWidgets(array(
      'id_alpza_miembro_asociados'     => new sfWidgetFormInputHidden(),
      'alpza_miembro_id_alpza_miembro' => new sfWidgetFormPropelChoice(array('model' => 'AlpzaMiembro', 'add_empty' => false)),
      'nombre_formal'                  => new sfWidgetFormInputText(),
      'sigla'                          => new sfWidgetFormInputText(),
      'tipo_institucion'               => new sfWidgetFormInputText(),
      'numero_identificacion'          => new sfWidgetFormInputText(),
      'ano_fundacion'                  => new sfWidgetFormDate(),
      'ano_ingreso_alpza'              => new sfWidgetFormDate(),
      'director_nombre'                => new sfWidgetFormInputText(),
      'director_email'                 => new sfWidgetFormInputText(),
      'delegado_nombre'                => new sfWidgetFormInputText(),
      'delegado_apellido'              => new sfWidgetFormInputText(),
      'delegado_cargo'                 => new sfWidgetFormInputText(),
      'delegado_profesion'             => new sfWidgetFormInputText(),
      'delegado_email'                 => new sfWidgetFormInputText(),
      'logo'                           => new sfWidgetFormInputText(),
      'direccion'                      => new sfWidgetFormInputText(),
      'codigo_postal'                  => new sfWidgetFormInputText(),
      'pais'                           => new sfWidgetFormInputText(),
      'telefono_cod_ciudad'            => new sfWidgetFormInputText(),
      'telefono_cod_pais'              => new sfWidgetFormInputText(),
      'telefono'                       => new sfWidgetFormInputText(),
      'celular'                        => new sfWidgetFormInputText(),
      'email'                          => new sfWidgetFormInputText(),
      'fax'                            => new sfWidgetFormInputText(),
      'sitio_web'                      => new sfWidgetFormInputText(),
      'descripcion'                    => new sfWidgetFormTextarea(),
      'mision'                         => new sfWidgetFormTextarea(),
      'vision'                         => new sfWidgetFormTextarea(),
      'objetivos'                      => new sfWidgetFormTextarea(),
      'acreditacion_aza'               => new sfWidgetFormInputText(),
      'acreditacion_iso14001'          => new sfWidgetFormInputText(),
      'acreditacion_iso9001'           => new sfWidgetFormInputText(),
      'acreditacion_otra'              => new sfWidgetFormInputText(),
      'asociacion_waza'                => new sfWidgetFormInputText(),
      'asociacion_aza'                 => new sfWidgetFormInputText(),
      'asociacion_eaza'                => new sfWidgetFormInputText(),
      'asociacion_ize'                 => new sfWidgetFormInputText(),
      'asociacion_amaczoa'             => new sfWidgetFormInputText(),
      'asociacion_isis'                => new sfWidgetFormInputText(),
      'asociacion_otra'                => new sfWidgetFormInputText(),
      'marca_anillo'                   => new sfWidgetFormInputText(),
      'marca_banda'                    => new sfWidgetFormInputText(),
      'marca_caliente'                 => new sfWidgetFormInputText(),
      'marca_fria'                     => new sfWidgetFormInputText(),
      'marca_microchip'                => new sfWidgetFormInputText(),
      'marca_natura'                   => new sfWidgetFormInputText(),
      'marca_piquete'                  => new sfWidgetFormInputText(),
      'marca_raya'                     => new sfWidgetFormInputText(),
      'marca_tatuaje'                  => new sfWidgetFormInputText(),
      'marca_otra'                     => new sfWidgetFormInputText(),
      'visitas_anuales'                => new sfWidgetFormInputText(),
      'propietario'                    => new sfWidgetFormInputText(),
      'administrador'                  => new sfWidgetFormInputText(),
      'lucro'                          => new sfWidgetFormInputText(),
      'ofrece_asesoria'                => new sfWidgetFormInputText(),
      'personal_permanente'            => new sfWidgetFormInputText(),
      'personal_temporal'              => new sfWidgetFormInputText(),
      'horario_atencion'               => new sfWidgetFormTextarea(),
      'objetivo'                       => new sfWidgetFormTextarea(),
      'senalizacion_porcentaje'        => new sfWidgetFormInputText(),
      'zoologico_contacto'             => new sfWidgetFormInputText(),
      'boletin'                        => new sfWidgetFormInputText(),
      'programa_enriquecimiento'       => new sfWidgetFormInputText(),
      'programa_entrenamiento'         => new sfWidgetFormInputText(),
      'programa_manejo_ambiental'      => new sfWidgetFormInputText(),
      'programa_medicina_preventiva'   => new sfWidgetFormInputText(),
      'consulta_externa_veterinaria'   => new sfWidgetFormInputText(),
      'show'                           => new sfWidgetFormInputText(),
      'documento_estrategico'          => new sfWidgetFormInputText(),
      'proyecto_conservacion_exsitu'   => new sfWidgetFormInputText(),
      'proyecto_conservacion_insitu'   => new sfWidgetFormInputText(),
      'asociacion_lista_asociaciones'  => new sfWidgetFormInputText(),
      'asociacion_lista_instituciones' => new sfWidgetFormInputText(),
      'asociacion_apoyo_desde_alpza'   => new sfWidgetFormInputText(),
      'asociacion_apoyo_hacia_alpza'   => new sfWidgetFormInputText(),
      'asociacion_estatutos'           => new sfWidgetFormInputText(),
      'asociacion_organigrama'         => new sfWidgetFormInputText(),
      'asociacion_panorama_pais'       => new sfWidgetFormInputText(),
		));

		$this->setValidators(array(
      'id_alpza_miembro_asociados'     => new sfValidatorChoice(array('choices' => array($this->getObject()->getIdAlpzaMiembroAsociados()), 'empty_value' => $this->getObject()->getIdAlpzaMiembroAsociados(), 'required' => false)),
      'alpza_miembro_id_alpza_miembro' => new sfValidatorPropelChoice(array('model' => 'AlpzaMiembro', 'column' => 'id_alpza_miembro')),
      'nombre_formal'                  => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'sigla'                          => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'tipo_institucion'               => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'numero_identificacion'          => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'ano_fundacion'                  => new sfValidatorDate(array('required' => false)),
      'ano_ingreso_alpza'              => new sfValidatorDate(array('required' => false)),
      'director_nombre'                => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'director_email'                 => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'delegado_nombre'                => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'delegado_apellido'              => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'delegado_cargo'                 => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'delegado_profesion'             => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'delegado_email'                 => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'logo'                           => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'direccion'                      => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'codigo_postal'                  => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'pais'                           => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'telefono_cod_ciudad'            => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'telefono_cod_pais'              => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'telefono'                       => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'celular'                        => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'email'                          => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'fax'                            => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'sitio_web'                      => new sfValidatorString(array('max_length' => 254, 'required' => false)),
      'descripcion'                    => new sfValidatorString(array('required' => false)),
      'mision'                         => new sfValidatorString(array('required' => false)),
      'vision'                         => new sfValidatorString(array('required' => false)),
      'objetivos'                      => new sfValidatorString(array('required' => false)),
      'acreditacion_aza'               => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'acreditacion_iso14001'          => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'acreditacion_iso9001'           => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'acreditacion_otra'              => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'asociacion_waza'                => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'asociacion_aza'                 => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'asociacion_eaza'                => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'asociacion_ize'                 => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'asociacion_amaczoa'             => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'asociacion_isis'                => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'asociacion_otra'                => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'marca_anillo'                   => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'marca_banda'                    => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'marca_caliente'                 => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'marca_fria'                     => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'marca_microchip'                => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'marca_natura'                   => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'marca_piquete'                  => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'marca_raya'                     => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'marca_tatuaje'                  => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'marca_otra'                     => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'visitas_anuales'                => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'propietario'                    => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'administrador'                  => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'lucro'                          => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'ofrece_asesoria'                => new sfValidatorInteger(array('min' => -2147483648, 'max' => 2147483647, 'required' => false)),
      'personal_permanente'            => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'personal_temporal'              => new sfValidatorString(array('max_length' => 45, 'required' => false)),
      'horario_atencion'               => new sfValidatorString(array('required' => false)),
      'objetivo'                       => new sfValidatorString(array('required' => false)),
      'senalizacion_porcentaje'        => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'zoologico_contacto'             => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'boletin'                        => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'programa_enriquecimiento'       => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'programa_entrenamiento'         => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'programa_manejo_ambiental'      => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'programa_medicina_preventiva'   => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'consulta_externa_veterinaria'   => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'show'                           => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'documento_estrategico'          => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'proyecto_conservacion_exsitu'   => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'proyecto_conservacion_insitu'   => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'asociacion_lista_asociaciones'  => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'asociacion_lista_instituciones' => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'asociacion_apoyo_desde_alpza'   => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'asociacion_apoyo_hacia_alpza'   => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'asociacion_estatutos'           => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'asociacion_organigrama'         => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'asociacion_panorama_pais'       => new sfValidatorString(array('max_length' => 100, 'required' => false)),
		));

		$this->widgetSchema->setNameFormat('alpza_miembro_asociados[%s]');

		$this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

		parent::setup();
	}

	public function getModelName()
	{
		return 'AlpzaMiembroAsociados';
	}


}
