<?php

/**
 * AlpzaMiembroAsociados filter form base class.
 *
 * @package    alpzaDev
 * @subpackage filter
 * @author     Your name here
 */
abstract class BaseAlpzaMiembroAsociadosFormFilter extends BaseFormFilterPropel
{
	public function setup()
	{
		$this->setWidgets(array(
      'alpza_miembro_id_alpza_miembro' => new sfWidgetFormPropelChoice(array('model' => 'AlpzaMiembro', 'add_empty' => true)),
      'nombre_formal'                  => new sfWidgetFormFilterInput(),
      'sigla'                          => new sfWidgetFormFilterInput(),
      'tipo_institucion'               => new sfWidgetFormFilterInput(),
      'numero_identificacion'          => new sfWidgetFormFilterInput(),
      'ano_fundacion'                  => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'ano_ingreso_alpza'              => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate())),
      'director_nombre'                => new sfWidgetFormFilterInput(),
      'director_email'                 => new sfWidgetFormFilterInput(),
      'delegado_nombre'                => new sfWidgetFormFilterInput(),
      'delegado_apellido'              => new sfWidgetFormFilterInput(),
      'delegado_cargo'                 => new sfWidgetFormFilterInput(),
      'delegado_profesion'             => new sfWidgetFormFilterInput(),
      'delegado_email'                 => new sfWidgetFormFilterInput(),
      'logo'                           => new sfWidgetFormFilterInput(),
      'direccion'                      => new sfWidgetFormFilterInput(),
      'codigo_postal'                  => new sfWidgetFormFilterInput(),
      'pais'                           => new sfWidgetFormFilterInput(),
      'telefono_cod_ciudad'            => new sfWidgetFormFilterInput(),
      'telefono_cod_pais'              => new sfWidgetFormFilterInput(),
      'telefono'                       => new sfWidgetFormFilterInput(),
      'celular'                        => new sfWidgetFormFilterInput(),
      'email'                          => new sfWidgetFormFilterInput(),
      'fax'                            => new sfWidgetFormFilterInput(),
      'sitio_web'                      => new sfWidgetFormFilterInput(),
      'descripcion'                    => new sfWidgetFormFilterInput(),
      'mision'                         => new sfWidgetFormFilterInput(),
      'vision'                         => new sfWidgetFormFilterInput(),
      'objetivos'                      => new sfWidgetFormFilterInput(),
      'acreditacion_aza'               => new sfWidgetFormFilterInput(),
      'acreditacion_iso14001'          => new sfWidgetFormFilterInput(),
      'acreditacion_iso9001'           => new sfWidgetFormFilterInput(),
      'acreditacion_otra'              => new sfWidgetFormFilterInput(),
      'asociacion_waza'                => new sfWidgetFormFilterInput(),
      'asociacion_aza'                 => new sfWidgetFormFilterInput(),
      'asociacion_eaza'                => new sfWidgetFormFilterInput(),
      'asociacion_ize'                 => new sfWidgetFormFilterInput(),
      'asociacion_amaczoa'             => new sfWidgetFormFilterInput(),
      'asociacion_isis'                => new sfWidgetFormFilterInput(),
      'asociacion_otra'                => new sfWidgetFormFilterInput(),
      'marca_anillo'                   => new sfWidgetFormFilterInput(),
      'marca_banda'                    => new sfWidgetFormFilterInput(),
      'marca_caliente'                 => new sfWidgetFormFilterInput(),
      'marca_fria'                     => new sfWidgetFormFilterInput(),
      'marca_microchip'                => new sfWidgetFormFilterInput(),
      'marca_natura'                   => new sfWidgetFormFilterInput(),
      'marca_piquete'                  => new sfWidgetFormFilterInput(),
      'marca_raya'                     => new sfWidgetFormFilterInput(),
      'marca_tatuaje'                  => new sfWidgetFormFilterInput(),
      'marca_otra'                     => new sfWidgetFormFilterInput(),
      'visitas_anuales'                => new sfWidgetFormFilterInput(),
      'propietario'                    => new sfWidgetFormFilterInput(),
      'administrador'                  => new sfWidgetFormFilterInput(),
      'lucro'                          => new sfWidgetFormFilterInput(),
      'ofrece_asesoria'                => new sfWidgetFormFilterInput(),
      'personal_permanente'            => new sfWidgetFormFilterInput(),
      'personal_temporal'              => new sfWidgetFormFilterInput(),
      'horario_atencion'               => new sfWidgetFormFilterInput(),
      'objetivo'                       => new sfWidgetFormFilterInput(),
      'senalizacion_porcentaje'        => new sfWidgetFormFilterInput(),
      'zoologico_contacto'             => new sfWidgetFormFilterInput(),
      'boletin'                        => new sfWidgetFormFilterInput(),
      'programa_enriquecimiento'       => new sfWidgetFormFilterInput(),
      'programa_entrenamiento'         => new sfWidgetFormFilterInput(),
      'programa_manejo_ambiental'      => new sfWidgetFormFilterInput(),
      'programa_medicina_preventiva'   => new sfWidgetFormFilterInput(),
      'consulta_externa_veterinaria'   => new sfWidgetFormFilterInput(),
      'show'                           => new sfWidgetFormFilterInput(),
      'documento_estrategico'          => new sfWidgetFormFilterInput(),
      'proyecto_conservacion_exsitu'   => new sfWidgetFormFilterInput(),
      'proyecto_conservacion_insitu'   => new sfWidgetFormFilterInput(),
      'asociacion_lista_asociaciones'  => new sfWidgetFormFilterInput(),
      'asociacion_lista_instituciones' => new sfWidgetFormFilterInput(),
      'asociacion_apoyo_desde_alpza'   => new sfWidgetFormFilterInput(),
      'asociacion_apoyo_hacia_alpza'   => new sfWidgetFormFilterInput(),
      'asociacion_estatutos'           => new sfWidgetFormFilterInput(),
      'asociacion_organigrama'         => new sfWidgetFormFilterInput(),
      'asociacion_panorama_pais'       => new sfWidgetFormFilterInput(),
		));

		$this->setValidators(array(
      'alpza_miembro_id_alpza_miembro' => new sfValidatorPropelChoice(array('required' => false, 'model' => 'AlpzaMiembro', 'column' => 'id_alpza_miembro')),
      'nombre_formal'                  => new sfValidatorPass(array('required' => false)),
      'sigla'                          => new sfValidatorPass(array('required' => false)),
      'tipo_institucion'               => new sfValidatorPass(array('required' => false)),
      'numero_identificacion'          => new sfValidatorPass(array('required' => false)),
      'ano_fundacion'                  => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'ano_ingreso_alpza'              => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'director_nombre'                => new sfValidatorPass(array('required' => false)),
      'director_email'                 => new sfValidatorPass(array('required' => false)),
      'delegado_nombre'                => new sfValidatorPass(array('required' => false)),
      'delegado_apellido'              => new sfValidatorPass(array('required' => false)),
      'delegado_cargo'                 => new sfValidatorPass(array('required' => false)),
      'delegado_profesion'             => new sfValidatorPass(array('required' => false)),
      'delegado_email'                 => new sfValidatorPass(array('required' => false)),
      'logo'                           => new sfValidatorPass(array('required' => false)),
      'direccion'                      => new sfValidatorPass(array('required' => false)),
      'codigo_postal'                  => new sfValidatorPass(array('required' => false)),
      'pais'                           => new sfValidatorPass(array('required' => false)),
      'telefono_cod_ciudad'            => new sfValidatorPass(array('required' => false)),
      'telefono_cod_pais'              => new sfValidatorPass(array('required' => false)),
      'telefono'                       => new sfValidatorPass(array('required' => false)),
      'celular'                        => new sfValidatorPass(array('required' => false)),
      'email'                          => new sfValidatorPass(array('required' => false)),
      'fax'                            => new sfValidatorPass(array('required' => false)),
      'sitio_web'                      => new sfValidatorPass(array('required' => false)),
      'descripcion'                    => new sfValidatorPass(array('required' => false)),
      'mision'                         => new sfValidatorPass(array('required' => false)),
      'vision'                         => new sfValidatorPass(array('required' => false)),
      'objetivos'                      => new sfValidatorPass(array('required' => false)),
      'acreditacion_aza'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'acreditacion_iso14001'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'acreditacion_iso9001'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'acreditacion_otra'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'asociacion_waza'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'asociacion_aza'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'asociacion_eaza'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'asociacion_ize'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'asociacion_amaczoa'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'asociacion_isis'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'asociacion_otra'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'marca_anillo'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'marca_banda'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'marca_caliente'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'marca_fria'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'marca_microchip'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'marca_natura'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'marca_piquete'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'marca_raya'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'marca_tatuaje'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'marca_otra'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'visitas_anuales'                => new sfValidatorPass(array('required' => false)),
      'propietario'                    => new sfValidatorPass(array('required' => false)),
      'administrador'                  => new sfValidatorPass(array('required' => false)),
      'lucro'                          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ofrece_asesoria'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'personal_permanente'            => new sfValidatorPass(array('required' => false)),
      'personal_temporal'              => new sfValidatorPass(array('required' => false)),
      'horario_atencion'               => new sfValidatorPass(array('required' => false)),
      'objetivo'                       => new sfValidatorPass(array('required' => false)),
      'senalizacion_porcentaje'        => new sfValidatorPass(array('required' => false)),
      'zoologico_contacto'             => new sfValidatorPass(array('required' => false)),
      'boletin'                        => new sfValidatorPass(array('required' => false)),
      'programa_enriquecimiento'       => new sfValidatorPass(array('required' => false)),
      'programa_entrenamiento'         => new sfValidatorPass(array('required' => false)),
      'programa_manejo_ambiental'      => new sfValidatorPass(array('required' => false)),
      'programa_medicina_preventiva'   => new sfValidatorPass(array('required' => false)),
      'consulta_externa_veterinaria'   => new sfValidatorPass(array('required' => false)),
      'show'                           => new sfValidatorPass(array('required' => false)),
      'documento_estrategico'          => new sfValidatorPass(array('required' => false)),
      'proyecto_conservacion_exsitu'   => new sfValidatorPass(array('required' => false)),
      'proyecto_conservacion_insitu'   => new sfValidatorPass(array('required' => false)),
      'asociacion_lista_asociaciones'  => new sfValidatorPass(array('required' => false)),
      'asociacion_lista_instituciones' => new sfValidatorPass(array('required' => false)),
      'asociacion_apoyo_desde_alpza'   => new sfValidatorPass(array('required' => false)),
      'asociacion_apoyo_hacia_alpza'   => new sfValidatorPass(array('required' => false)),
      'asociacion_estatutos'           => new sfValidatorPass(array('required' => false)),
      'asociacion_organigrama'         => new sfValidatorPass(array('required' => false)),
      'asociacion_panorama_pais'       => new sfValidatorPass(array('required' => false)),
		));

		$this->widgetSchema->setNameFormat('alpza_miembro_asociados_filters[%s]');

		$this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

		parent::setup();
	}

	public function getModelName()
	{
		return 'AlpzaMiembroAsociados';
	}

	public function getFields()
	{
		return array(
      'id_alpza_miembro_asociados'     => 'Number',
      'alpza_miembro_id_alpza_miembro' => 'ForeignKey',
      'nombre_formal'                  => 'Text',
      'sigla'                          => 'Text',
      'tipo_institucion'               => 'Text',
      'numero_identificacion'          => 'Text',
      'ano_fundacion'                  => 'Date',
      'ano_ingreso_alpza'              => 'Date',
      'director_nombre'                => 'Text',
      'director_email'                 => 'Text',
      'delegado_nombre'                => 'Text',
      'delegado_apellido'              => 'Text',
      'delegado_cargo'                 => 'Text',
      'delegado_profesion'             => 'Text',
      'delegado_email'                 => 'Text',
      'logo'                           => 'Text',
      'direccion'                      => 'Text',
      'codigo_postal'                  => 'Text',
      'pais'                           => 'Text',
      'telefono_cod_ciudad'            => 'Text',
      'telefono_cod_pais'              => 'Text',
      'telefono'                       => 'Text',
      'celular'                        => 'Text',
      'email'                          => 'Text',
      'fax'                            => 'Text',
      'sitio_web'                      => 'Text',
      'descripcion'                    => 'Text',
      'mision'                         => 'Text',
      'vision'                         => 'Text',
      'objetivos'                      => 'Text',
      'acreditacion_aza'               => 'Number',
      'acreditacion_iso14001'          => 'Number',
      'acreditacion_iso9001'           => 'Number',
      'acreditacion_otra'              => 'Number',
      'asociacion_waza'                => 'Number',
      'asociacion_aza'                 => 'Number',
      'asociacion_eaza'                => 'Number',
      'asociacion_ize'                 => 'Number',
      'asociacion_amaczoa'             => 'Number',
      'asociacion_isis'                => 'Number',
      'asociacion_otra'                => 'Number',
      'marca_anillo'                   => 'Number',
      'marca_banda'                    => 'Number',
      'marca_caliente'                 => 'Number',
      'marca_fria'                     => 'Number',
      'marca_microchip'                => 'Number',
      'marca_natura'                   => 'Number',
      'marca_piquete'                  => 'Number',
      'marca_raya'                     => 'Number',
      'marca_tatuaje'                  => 'Number',
      'marca_otra'                     => 'Number',
      'visitas_anuales'                => 'Text',
      'propietario'                    => 'Text',
      'administrador'                  => 'Text',
      'lucro'                          => 'Number',
      'ofrece_asesoria'                => 'Number',
      'personal_permanente'            => 'Text',
      'personal_temporal'              => 'Text',
      'horario_atencion'               => 'Text',
      'objetivo'                       => 'Text',
      'senalizacion_porcentaje'        => 'Text',
      'zoologico_contacto'             => 'Text',
      'boletin'                        => 'Text',
      'programa_enriquecimiento'       => 'Text',
      'programa_entrenamiento'         => 'Text',
      'programa_manejo_ambiental'      => 'Text',
      'programa_medicina_preventiva'   => 'Text',
      'consulta_externa_veterinaria'   => 'Text',
      'show'                           => 'Text',
      'documento_estrategico'          => 'Text',
      'proyecto_conservacion_exsitu'   => 'Text',
      'proyecto_conservacion_insitu'   => 'Text',
      'asociacion_lista_asociaciones'  => 'Text',
      'asociacion_lista_instituciones' => 'Text',
      'asociacion_apoyo_desde_alpza'   => 'Text',
      'asociacion_apoyo_hacia_alpza'   => 'Text',
      'asociacion_estatutos'           => 'Text',
      'asociacion_organigrama'         => 'Text',
      'asociacion_panorama_pais'       => 'Text',
		);
	}
}
